### ISSUE TITLE
Floating windows redraws; cleanup after closing

### ISSUE THREAD

**Issue by stacksmith** [cxxxr/lem#101]
Anomalies:

- Floating windows do not redraw last column (is it intentional? Drop shadow?)
- redraw after a floating window is canceled does not refresh the modeline!

To reproduce: 
- start lem-xcb
- key in `<M-x>slim<TAB>`
- The completion menu pops up.  Note that the view is 20 glyphs wide; after clear-eol only 19 characters are written!  Note the black hole on the modeline at the last position (19).
- key in `<Esc>` to cancel.
The modeline is not updated:

```
xcb: delete-view #<TEXTVIEW {1005238503}> 
xcb: interface-clear-eol view #<TEXTVIEW {100415B123}> x: 0 y 1
xcb: interface-redraw after: view #<TEXTVIEW {100415B123}> : NIL
xcb: interface-clear-eol view #<TEXTVIEW {10042D8C43}> x: 0 y 0
xcb: interface-print #<TEXTVIEW {10042D8C43}> (0 0) |M-x | attr:MINIBUFFER-PROMPT-ATTRIBUTE 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (4 0) |slim| attr:NIL 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (8 0) | | attr:CURSOR 
xcb: interface-redraw after: view #<TEXTVIEW {10042D8C43}> : T
xcb: interface-redraw-display: 
xcb: interface-clear-eol view #<TEXTVIEW {100415B123}> x: 0 y 1
xcb: interface-redraw after: view #<TEXTVIEW {100415B123}> : NIL
xcb: interface-clear-eol view #<TEXTVIEW {10042D8C43}> x: 0 y 0
xcb: interface-print #<TEXTVIEW {10042D8C43}> (0 0) |Key not found: Escape| attr:NIL 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (21 0) | | attr:CURSOR 
xcb: interface-redraw after: view #<TEXTVIEW {10042D8C43}> : T
xcb: interface-redraw-display: 
xcb: interface-clear-eol view #<TEXTVIEW {100415B123}> x: 0 y 1
xcb: interface-redraw after: view #<TEXTVIEW {100415B123}> : NIL
xcb: interface-clear-eol view #<TEXTVIEW {10042D8C43}> x: 0 y 0
xcb: interface-print #<TEXTVIEW {10042D8C43}> (0 0) |M-x | attr:MINIBUFFER-PROMPT-ATTRIBUTE 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (4 0) |slim| attr:NIL 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (8 0) | | attr:CURSOR 
xcb: interface-redraw after: view #<TEXTVIEW {10042D8C43}> : T
xcb: interface-redraw-display: 
xcb: interface-clear-eol view #<TEXTVIEW {100415B123}> x: 0 y 1
xcb: interface-redraw after: view #<TEXTVIEW {100415B123}> : NIL
xcb: interface-clear-eol view #<TEXTVIEW {10042D8C43}> x: 0 y 0
xcb: interface-print #<TEXTVIEW {10042D8C43}> (0 0) |M-x | attr:MINIBUFFER-PROMPT-ATTRIBUTE 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (4 0) |slim| attr:NIL 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (8 0) | | attr:CURSOR 
xcb: interface-redraw after: view #<TEXTVIEW {10042D8C43}> : T
xcb: interface-redraw-display: 
xcb: interface-clear-eol view #<TEXTVIEW {100415B123}> x: 0 y 1
xcb: interface-redraw after: view #<TEXTVIEW {100415B123}> : NIL
xcb: interface-clear-eol view #<TEXTVIEW {10042D8C43}> x: 0 y 0
xcb: interface-print #<TEXTVIEW {10042D8C43}> (0 0) |M-x | attr:MINIBUFFER-PROMPT-ATTRIBUTE 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (4 0) |slim| attr:NIL 
xcb: interface-print #<TEXTVIEW {10042D8C43}> (8 0) | | attr:CURSOR 
xcb: interface-redraw after: view #<TEXTVIEW {10042D8C43}> : T
xcb: interface-redraw-display: 
```

**Comment by stacksmith** [comment]
Looking at ncurses frontend, I think I see the issue (correct me if I am wrong).

it looks like `interface-redraw-view-after` forces a redraw of the modeline.  Curses caches the view, so it updates.  This behavior is specifict to ncurses.  In addition, deleting an ncurses window probably restores the modeline anyway.

For other frontends, it's a problem, since it requires the frontend to cache the modeline.  This is not consistent with the interface protocol - everywhere else it explicitly redraws all other text.

If I am not mistaken, the fix requires the update code to redraw modeline text explicitly after floating window is removed.

**Comment by stacksmith** [comment]
For now, I will force a redraw when a view is deleted.  It sort of works, but adds yet another unnecessary redraw.  The issue should be addressed.

**Comment by cxxxr** [comment]
> Floating windows do not redraw last column (is it intentional? Drop shadow?)

fixed. https://github.com/cxxxr/lem/commit/eefe27f2924c29d28c6b6d1d4519b376009a1bdf

floating window problem is probably [here](https://github.com/cxxxr/lem/blob/eefe27f2924c29d28c6b6d1d4519b376009a1bdf/lem-core/window.lisp#L1001)

**Comment by stacksmith** [comment]
Great, thank you.
