### ISSUE TITLE
Horizontal window splits need rethinking

### ISSUE THREAD

**Issue by stacksmith** [cxxxr/lem#103]
Side-by-side window split layout logic assumes the separator is 1-glyph wide.  

The separator is not explicitly redrawn.

Frontend makes a guess about the separator presence by checking that the view simultaneously (1) has a modeline and (2) is not at left edge;  in this case, it explicitly draws a vertical line at x-1 column (see frontend-ncurses)

Not high priority, but this needs to be cleaned up at some point in main logic.

Ideally, the separator should not be explicit or relate to the grid in any way.  Main logic should not account for separator width; frontends should figure out the position, and draw an appropriate separator.  Ncurses, for instance, can add an extra character, while X can add a single-pixel line separator.

**Comment by snmsts** [comment]
I translate it to Japanese intend to help @cxxxr 

````
題: 縦window分割について要再考

ウィンドウを並べた際のレイアウトロジックは分割線を1グリフ幅と見做している。

分割線は明示的に再描画されない。

フロントエンドは分割線の存在をビューに (1)モードラインが存在し(2) 左端ではないことを同時にみたすかどうかで調べている。この場合にx-1列に縦線を明示的に引いている(frontend-ncurses参照)

優先度は高くはないが、これはmain logic内でcleanにされるべき。(さの:cleanに妥当な日本語はわからない 、意味は感じられるはず。at some pointも訳省略)

理想的には、明示的というかgridとの関係無いようにすべき。main logicは分割線の幅に依存すべきではなく、frontendがその位置を把握し描画すべき。たとえばncursesでは一文字追加し、Xでは1pixelの分割線を引くようにできるように。
```

I'll translate Japanese to English as well. What's your idea, @cxxxr ?

**Comment by cxxxr** [comment]
通訳助かります。

分割線が必要なのはncursesのような文字単位で描画しているフロントエンドだけで、
electronの描画ではcanvasのborder-styleがその役割を担っているので不要でした。
それ以外のGUIフロントエンドでもelectronと同じく、ウィンドウの枠が分割線を引くはずです。
xcbでも他のフロントエンドとは違う処理が必要なはずで、xcb側でアドホックに枠線を引くことになると思います。

**Comment by snmsts** [comment]
このissue自体は、「アドホックさをmain logic側でどうにかできない？」という事なんだけど。
その回答だとちょっと噛みあわないね。お前ここを見ろよ…的なのないかね？

**Comment by stacksmith** [comment]
それは結構です。

おそらく、将来的には、 "border-style"はグローバルであり、フロントエンドは何をすべきかを選択できるでしょうか？

悪い日本語の謝罪（Google翻訳:)

**Comment by cxxxr** [comment]
今の所、そのアドホックな処理はinterface-redraw-view-afterで行うのが適切かと思います。

**Comment by snmsts** [comment]
@stacksmith sorry for delay and in that sense. I should say sorry for my bad English.
If you wrote the sentences in English before translate, I prefer read it in English cause most of the case It's easier to understand.

**Comment by stacksmith** [comment]
@snmsts, thank you.  I will stick to English.  I am happy to leave interface-redraw-view-after as is.
