### ISSUE TITLE
scratchで#p"test"が"test"と評価される

### ISSUE THREAD

**Issue by KeenS** [cxxxr/lem#11]
本来は `#p"test"` と評価される筈。 リードマクロの扱い難しいですし仕様かもしれませんが。

再現手順

1. lemを起動
2. `#p"test"` と入力する
3. `C-j`

**Comment by cxxxr** [comment]
S式単位のカーソルの移動で"の前のpで止まるようです
emacsでも同じはずですがどうでしょう

**Comment by KeenS** [comment]
emacs lispはリードマクロがないのでこのような問題は発生しませんね。というか逆向きにもパース出来るように文法が配慮して作られてます。

emacs上のcommon lispだと確かに"test"と評価されるようですね。じゃあ仕様ということで。

**Comment by cxxxr** [comment]
e0078d0e4c46a2baac4a29bdc106b3c3fb6e2d4a
出来ました
