### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by stacksmith** [cxxxr/lem#118]
In reference to fbar pull request https://github.com/cxxxr/lem/pull/117, and generally:

Could you please explain:

- How to resolve a mouse position to a view/buffer position and move the cursor accordingly;
- How to set a background color for an entire floating window;
- How to preserve state of a view/window/buffer/point, perform some actions (display a floating window, edit another window, etc) and restore state to exactly the same position;
- How to switch focus to a different view;
- How to scroll the entire view, not a single line in a view;
- The meaning of the different `point` objects: %window-point , buffer-point, window-view point, etc.  
- Are all points correct after the text is modified?

I have made some guesses, but I suspect there are better ways.

Thank you

**Comment by hiroki802** [comment]
[fbar pull request #117](https://github.com/cxxxr/lem/pull/117)や全体に関わることについて:

以下の点について、説明してもらえませんか？

1. どのようにマウスの位置をview/bufferの位置に移して、マウスカーソルの位置をそれに応じて動かすか
2. どのように変動するウィンドウ全体の背景色を決定するか
3. どのようにview/window/buffer/pointの状態を保存して実行しているか（変動するウィンドウを表示して、他のウィンドウを表示する等）。また、どのように状態を全く同じ場所に復元しているか。
4. どのように他のviewにfocusを移動させるか
5. １つのviewを一行ずつスクロールするのではなく、どのように画面全体のviewをスクロールするか。
6. 様々なpointオブジェクトの違いは何か。window-point , buffer-point, window-view pointなど。
7. 全てのポイントは、テキストが書きけられた後、更新されているのかどうか。

以上について自分なりに推測をしていますが、改善策があるのではないかと考えています。
敬具

**Comment by cxxxr** [comment]
1,2,3,5: can't do it.
4: `(setf current-window)`
6:
%window-point: old buffer location
buffer-point: cursor point of buffer
window-view-point: first line of displayed window

7: see [here](http://www.lispworks.com/documentation/lw71/EDUG-U/html/eduser-u-76.htm#pgfId-901995)

**Comment by stacksmith** [comment]
Thank you
