### ISSUE TITLE
ミニバッファでのキーバインド

### ISSUE THREAD

**Issue by KeenS** [cxxxr/lem#12]
ミニバッファでキーがバインドされていないようです。キーバインドがあると便利ですね。

因みにEmacsはmini-buffer-modeを作ってキーバインドを割り当てているようです。

**Comment by cxxxr** [comment]
たしかにその方がいいと思います
今ある細かな問題が落ち着いたらミニバッファまわりは改善させたい

**Comment by KeenS** [comment]
ありがとうございます!
