### ISSUE TITLE
Line-numbering should not be global?

### ISSUE THREAD

**Issue by stacksmith** [cxxxr/lem#131]
It would be nice to be able to selectively turn on/off line numbering, on a per-window or per-buffer basis.

**Comment by stacksmith** [comment]
私は行番号を個別にオンまたはオフにしたい。 どう思いますか？

**Comment by cxxxr** [comment]
`toggle-line-numbers`で有効になる機能のことですか？

**Comment by stacksmith** [comment]
すべてのウィンドウが同時に変更されます：1つのウィンドウまたはバッファを変更できますか？

**Comment by stacksmith** [comment]
私は誤解している可能性が高いです。 トグルコマンドを適用すると、すべてのウィンドウが行番号をオンにしているようです。 トリックはありますか？
It is highly likely that I misunderstood. Applying the toggle command seems that all windows are turning on line numbers. Is there a trick?

**Comment by cxxxr** [comment]
指定したバッファで無効化出来るようにしました。

`(setf (variable-value 'lem.line-numbers:line-numbers :buffer buffer) nil)`

**Comment by stacksmith** [comment]
優れた！

現在のバッファで作業するコマンドを追加することは可能ですか？

どうもありがとうございました

Excellent!  Is it possible to add a command to work with the current buffer?

**Comment by stacksmith** [comment]
多分 "toggle-line-numbers" 対照的に "toggle-all-line-numbers"
