### ISSUE TITLE
vi-mode r does not work

### ISSUE THREAD

**Issue by stacksmith** [cxxxr/lem#133]
"Not mark in this buffer"

Somehow, (check-marked) is called.

@gos-k Any ideas?

**Comment by stacksmith** [comment]
I don't think command (vi-replace-char) should have "r" in it - it is not an ex-command...

**Comment by stacksmith** [comment]
What does "r" in define-command mean?

**Comment by cxxxr** [comment]
https://github.com/cxxxr/lem/commit/5239cc614c661115ef9e7d4b09ce457af0351a57

**Comment by stacksmith** [comment]
define-commandで "r"は何を意味しますか？

**Comment by cxxxr** [comment]
regionの頭文字です

**Comment by stacksmith** [comment]
ありがとう、それは私が思ったものです。
