### ISSUE TITLE
lem doesn't work without clipboard.

### ISSUE THREAD

**Issue by asciian** [cxxxr/lem#134]
lem `C-w` and `C-y` works with `trivial-clipboard` now. `trivial-clipboard` uses clipboard provided by the desktop environments which isn't operation system. it's means that we cannot uses these functions in the system which doesn't have it. I propose you that lem has two clipboards. One is `trivial-clipboard` and another is global variables of editor.

**Comment by snmsts** [comment]
on xyzzy(https://github.com/xyzzy-022/xyzzy/commits/develop) 
there are two term for the concept. ``selection`` which are way to refer system's clipboard.
and ``region`` refer almost same as emacs's region which are used to kill some part of buffer.
User can select algorithm how those two to sync (or not).

Japanese further explanation here http://hie.s64.xrea.com/xyzzy/note/region-selection.html#2

**Comment by snmsts** [comment]
clipboard functions are separated from kill-ring now. I'll close this issue. later.
