### ISSUE TITLE
English to Japanese translation policy on issues

### ISSUE THREAD

**Issue by snmsts** [cxxxr/lem#136]
##　issueの訳出方針
- [ ] 訳出必要のラベルを作って@cxxxr さんには運用してもらう。(ここの訳者は不必要な部分を和訳したいわけではないので。Reader should apply label an issue ``need translation`` to omit unnecessarily translation.
- [ ] このissueは@cxxxr に納得してラベルを切ってもらったら@snmsts がcloseする。 This issue intend to confirm  @cxxxr and when it done I'll close it.

**Comment by hiroki802** [comment]
了解しました

**Comment by snmsts** [comment]
almost no japanese are used in lem development.
