### ISSUE TITLE
info-popupの挙動?

### ISSUE THREAD

**Issue by snmsts** [cxxxr/lem#14]
M-x descr [tab]bi [tab] [C-m] の際*bindings*バッファがカーソル移動で瞬殺されてしまいます。
*Completion*バッファを閉じるためのフラグか何かが
影響しているように見えますがいかがでしょうか。

**Comment by cxxxr** [comment]
ありがとうございます
たしかに補完用バッファを区別させていないのが影響してます

**Comment by snmsts** [comment]
ありがとうございます。
