### ISSUE TITLE
add a dependency: keyboard-layout to handle different keyboard layout

### ISSUE THREAD

**Issue by t-cool** [cxxxr/lem#171]
Please add a dependency about keyboard-layout to handle JIS keyboard.

**Comment by t-cool** [comment]
@picospuch 
There was a system error on Bountysource and the settlement was done twice.
Can you send a claim as $15?

**Comment by picospuch** [comment]
No, I have managed but failed to change bounty amount. The 'claim' step is after closing this issue. There's no any other options after filling 'Getting Started' form.

**Comment by picospuch** [comment]
Not work... Thank you for your generosity. Don't mind. I have received a $15 bounty.

**Comment by t-cool** [comment]
Okay!

**Comment by t-cool** [comment]
@picospuch 
Can you send a claim on BS as $15?
I'll approve it.

**Comment by picospuch** [comment]
@t-cool :-)
this is what i saw on bountysource, no place to set bounty amount.

![invitersync](https://user-images.githubusercontent.com/2293057/37508445-0e7b75ce-292e-11e8-94fa-381f35af38de.gif)

**Comment by t-cool** [comment]
@picospuch 
Okay! I'll release $30.
I hope you'd help me with another issue in the future!

**Comment by picospuch** [comment]
@t-cool
As a javascripter, I'm happy to help lisper ;-)

**Comment by t-cool** [comment]
@picospuch 
Thanks! I released the budget.

**Comment by t-cool** [comment]
@picospuch 

Can you solve this issue?
https://www.bountysource.com/orders/87065?receipt=1

**Comment by picospuch** [comment]
@t-cool I have not tried in practice, but it seems that Hunchentoot, the web server did not find the path to your images according to the backtrace you pasted. Try to use full path of directories instead of '~' in path.

**Comment by t-cool** [comment]
@picospuch 
Thank you for your reply.
I read the code one by one, and I made a mistake on the slideshow's URI.
The URI should be "http://localhost:8080/slideshows/lolcat" but I did "http://localhost:8080/slideshows/lolcat/"
