### ISSUE TITLE
lem:expand-file-name returns an absolute path at '/'

### ISSUE THREAD

**Issue by fukamachi** [cxxxr/lem#214]
`lem:expand-file-name` returns a invalid path starts with '/' if the first argument seems to be a relative one.

```common-lisp
(lem:expand-file-name "test")
;=> "/test"
(lem:expand-file-name "")
;=> "/"
```

On Emacs, it returns an absolute pathname at the current working directory.

```emacs-lisp
(expand-file-name "test")
;=> "/Users/fukamachi/test"
(expand-file-name "")
;=> "/Users/fukamachi"
```

**Comment by cxxxr** [comment]
https://github.com/cxxxr/lem/commit/f5a71db99833c43fa7cba9d9eb60db219f67cc0d
