### ISSUE TITLE
表示可能桁数を越える入力があった時の表示がおかしい

### ISSUE THREAD

**Issue by KeenS** [cxxxr/lem#22]
表示可能桁数を越える文字数がある行は溢れた文字が端の方に隠れる仕様のようですが、端の方の文字を表示させようと横スクロールに相当することをしようとした時に、その行しかスクロールされず他の行はそのまま表示されてしまうようです。

例えば表示可能桁数が80の時にバッファの内容が

```
aaa
bbb........100 times ....bbb
```

だと、表示上は

```
aaa
bbb...79 times...bb$
```

となります。1桁目から80桁目までを表示しています。
この時2行目にカーソルを合わせ、 `C-e` するとカーソルが100桁目にいくので表示されるのは21桁目から100桁目までの筈です。しかし実際には

```
aaa
$bb...79 times...bbb
```

と、1桁目から3桁目にある`aaa`が表示されてしまいます。恐らくカーソルが合わさっている行しか横スクロールしていないのだと思います。

**Comment by cxxxr** [comment]
その行だけ横スクロールするのはnanoでもmicro emacsでもjedでも同じです

lemの場合は手抜きの実装でカーソル位置が常に一番後ろに来るようになってますが

**Comment by KeenS** [comment]
仕様ならば問題ありません。
