### ISSUE TITLE
[バグ] scratchバッファで何度かC-jするとハングする

### ISSUE THREAD

**Issue by KeenS** [cxxxr/lem#24]
6~8回でハングします。

# 再現手順
1. lemを立ち上げる
2. `1`と入力する
3. `C-j`を8回繰り返す

# その他
* sbcl 1.2.15
* lem ﻿﻿28e292a518f891aac2ca2c2f661e91714c023fe9
* Mac Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

**Comment by cxxxr** [comment]
評価するときに別のスレッドを作っててその辺りが原因かもしれません

sbcl 1.2.16でLinux debian 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) i686 GNU/Linuxですがこの環境では何百回しても動きます

ccl1.10でも再現しません

以前別の環境でcclで動かした時は同じような事になったんですが

**Comment by KeenS** [comment]
捕捉するとハングしている時にSBCLはCPUを使っていません。単純に入力が無視されているようです。

**Comment by cxxxr** [comment]
bordeaux-threads:destroy-threadが正しくうごいてないとか
そもそもスレッドの扱い方が間違ってるのか
よくわかりませんがこの辺りのコードは全部無かったことにしたいですね
色々言いたいことはあるけどここに書くのは適切じゃ無さそう

**Comment by KeenS** [comment]
Emacsとかはスレッドじゃなくて非同期モデルで扱ってますねー。

**Comment by cxxxr** [comment]
それだと別のlispを起動してエディタから管理するということでしょうか

どっちにしてもバッファをスレッドセーフにしないと駄目そうです

**Comment by KeenS** [comment]
キー入力とかを非同期で扱ってます。lispの評価は同期なので重い処理をさせるとEmacsが固まりますね。

**Comment by cxxxr** [comment]
キー入力用のスレッドとそれを受け取って処理したり別のところから変更命令が来れば適用するスレッドに分ければうまく行きそうですね
さっきようやく思いつきました
これだと固まるのは仕方無さそうですね

**Comment by KeenS** [comment]
masterで直ってますね

**Comment by cxxxr** [comment]
masterではevalでスレッド作ってないので
