### ISSUE TITLE
Visualize whitespace/newline at EOL

### ISSUE THREAD

**Issue by fukamachi** [cxxxr/lem#276]
Like Emacs's whitespace-mode.

**Comment by snmsts** [comment]
use ``(variable-value 'after-syntax-scan-hook :global) `` https://github.com/cxxxr/lem/blob/master/lem-lisp-mode/paren-coloring.lisp

**Comment by cxxxr** [comment]
https://github.com/cxxxr/lem/tree/master/contrib/trailing-spaces
を追加しました
