### ISSUE TITLE
Some missing highlights in rust-mode

### ISSUE THREAD

**Issue by KeenS** [cxxxr/lem#279]
some highlights are missing compared to rust-mode of emacs or github.

* doc comment (after `///` )
* typenames (PascalCase names)
* symbol names (before `:` , `=` )
* macro names (before `!` )
* variables in macro (`$name`)
* path names (before `::` )
* attributes (`#[...]`)
* lifetimes/labels (`'name`)

Though None of them (emacs, github, lem) are complete, I want __attributes__ , __type names__ , __path names__, __function names__, and __macro names__ to be highlighted.

Emacs
![image](https://user-images.githubusercontent.com/4434568/44098331-e050d338-a01a-11e8-9760-3cf0ea20b413.png)

GitHub
![image](https://user-images.githubusercontent.com/4434568/44098369-033feb72-a01b-11e8-8c0d-7c37c850e0c3.png)

lem
![image](https://user-images.githubusercontent.com/4434568/44098399-1e44c96a-a01b-11e8-8644-da652629d92c.png)

and sample code is here
https://gist.github.com/KeenS/24bf5337c6c1232451322e1948a53055

**Comment by snmsts** [comment]
- [x] __attributes__ 
- [x]  __type names__ 
- [ ]  __path names__
- [ ] __function names__
- [ ] __macro names__
