### ISSUE TITLE
lem's icon

### ISSUE THREAD

**Issue by t-cool** [cxxxr/lem#283]
@cxxxr 
ご希望の通り、Shinmeraさんにアイコンの件を依頼しました。
英語に訳すので、希望を伝えてください。

I asked Shinmera about the lem's icon to make your wish come true.
Please tell him about your wish on this issue. I'll translate it into English.

**Comment by Shinmera** [comment]
よろしくお願いします。

**Comment by t-cool** [comment]
@cxxxr 
先ほど合意をいただいた内容を書き込みます。
* 形状はFirefoxに似た丸い形をしたもの
* 動物のレミングをモチーフにする
* レミングの数は1匹で、色は青色を基調にする
* 写実的な描写ではなく、抽象的な描写にする(Firefoxの狐のように)
* lemmingのイメージ元はhttps://en.wikipedia.org/wiki/Lemming#/media/File:Tunturisopuli_Lemmus_Lemmus.jpg

@Shinmera 
Hi, Shinmera.  Thank you again for accepting his request!
I'll write down the cxxxr's wishes as bellow:
* The shape is round like Firefox.
* The icon is designed in the motif of the animal lemming:
　https://en.wikipedia.org/wiki/Lemming#/media/File:Tunturisopuli_Lemmus_Lemmus.jpg
* It has one lemming in the icon.
* The color of the lemming is blue.
* The image is not realistic but abstract, such as Firefox.

Would it be possible to draw a few sketches and send them to cxxxr by e-mail?
He'll choose the image among them and ask you to make an icon based on the sketch.

I'd appreciate your help.
Hiroki, t-cool

**Comment by Shinmera** [comment]
Alright, I'll see what I can do.

**Comment by cxxxr** [comment]
よろしくお願いします

**Comment by Shinmera** [comment]
Sorry for the long wait! Here are a few sketches I made today. Please pick one of the five designs and I will make some more sketches based on it. I would recommend the first and third icon sketches. If none of the current sketches are good, please let me know, and I'll try to come up with something else.

遅くなってすみません！今日その落書きを描きました。その落書きの一つを選んでください。それでは私はその選択の新しい落書きを描きます。1と3は私のおすすめです。もしこの落書きはだめ、新しいい絵を描きようとする。

![sketches](http://studio.tymoon.eu/api/studio/file?id=1369)

Things to keep in mind about icon design:
* The icon should be simple, but distinct.
* The icon should be recognizable even at very small sizes.
* Grayscale or single-tone designs are preferrable, as they can easily be colourised and adapted to fit any background and context, unlike coloured variants.
* The amount of shapes should be minimised to aid the above points.

I'm afraid my Japanese is not good enough to translate all of this, and I apologise for any mistakes I made in what little I did translate.

**Comment by t-cool** [comment]
@Shinmera 
Thank you for the sketches!
They are all cute and he would love them!
I'll translate what you wrote in the last message just in case.

@cxxxr 
日本語に訳すので、メッセージを読んでください。
返信は日本語でも英語でもOKです。

**************************************************************

Sorry for the long wait! 
長く待たせてしまってすいません。

Here are a few sketches I made today. 
今日描いたスケッチをいくつかお見せします。

Please pick one of the five designs 
5つのデザインから1つを選んでください。

and I will make some more sketches based on it. 
選んでいただいたものを元に、さらにいくつかスケッチを描きます。

I would recommend the first and third icon sketches. 
1と3がオススメです。

If none of the current sketches are good, please let me know, and I'll try to come up with something else.
もしこの中で気に入ったものがなければ、そう伝えてください。何か別のものを思いつくように頑張ってみます。

**************************************************************

Things to keep in mind about icon design:
アイコンのデザインで気をつけたことは次の通りです：

The icon should be simple, but distinct.
シンプルである一方で、他とは全く違うものであること。
　　
The icon should be recognizable even at very small sizes.
アイコンのサイズが小さくても認識されること。

Grayscale or single-tone designs are preferrable, 
グレースケールか単一の色調であること。

as they can easily be colourised and adapted to fit any background and context, unlike coloured variants.
理由は、アイコンに色を加えることも容易なうえ、どんな背景や文脈にも適応できるからです。色をつけてデザインをする場合は、このようにはいきません。

The amount of shapes should be minimised to aid the above points.
上の条件を満たすために、形状(shape)の数は最小限にとどめるべきです。

I'm afraid my Japanese is not good enough to translate all of this, 
日本語に訳す自信がなかったので英語で書きました。

and I apologise for any mistakes I made in what little I did translate.
もし、翻訳で間違えていたら申し訳ないです。

**Comment by cxxxr** [comment]
@Shinmera 
スケッチありがとうございます。
1が良いと思うので、それを元に進めてほしいです。
よろしくお願いします。

**Comment by Shinmera** [comment]
Alright, here's some more sketches based on the first design. As before, please tell me what you like best.

![sketches-2](http://studio.tymoon.eu/api/studio/file?id=1370)

**Comment by t-cool** [comment]
@cxxxr 

Alright, here's some more sketches based on the first design. As before, please tell me what you like best.

了解です。1番目のデザインを元に、いくつかスケッチを描きました。前回と同じように、一番気に入ったスケッチの番号を伝えてください。

**Comment by cxxxr** [comment]
1でお願いします。

**Comment by snmsts** [comment]
Thank you @Shinmera for your effort.
I do understand your criteria. it is distinct and recognizable and simple tone. I love your cute design.
To see your more sketches post I felt it becomes too simplified that I have difficulty to find its motif was a lemming.

Is it possible to add more lemming feature? It might come from teeth ,form of surround mouth, short limbs ,round body, or what ever feature. I would appreciate if it is distinct from other mammals at least I hope the icon can recognized it is Rodents.

https://github.com/cxxxr/lem/issues/283#issuecomment-417838003

I have no idea about how to explain but among original choices I feel 2 and 5 has more lemming feature...
(just talking about feature)

@cxxxr what do you think?

@t-cool 英語の採点をお願いします

**Comment by cxxxr** [comment]
@snmsts 
必ずしもlemmingのアイコンがlemmingと認識できる必要は無いと考えています。
例として上げるとfireofx, iceweasel, seamonkey, emacs等がそうでした。

**Comment by Shinmera** [comment]
One of my initial problems when looking at references was that the lemmings don't have a lot of disinguishing features to incorporate into a design aside from the markings. I heavily advise against a design that shows the full body though, as it would require too many small details. 

Keep in mind as well, that the icon will usually be viewed at much smaller sizes than here. I apologise for not including smaller versions too earlier.

![image](https://user-images.githubusercontent.com/4833204/44954509-6b6ce100-aea3-11e8-88ea-741ac81f4447.png)

I also apologise for failing to mention that the shading shown here is not final. I'll make a few versions of the final icon with different colours and shadings for you to choose from.

**Comment by t-cool** [comment]
@Shinmera 
Thank you for taking your time and letting us view the sketches! It's a good opportunity to share opinions among contributors. I hope this discussion will lead to the best result and we'll make a good relationship through this task. 

@snmsts
　I read your requests. The point is that it's better to add some features so that users can recognize the icon as a lemming.  And Shinmera pointed out that it's hard to add some features of lemmings in the image because the animal has few distinguishing features than other mammals. After that, cxxxr said that we don't have to recognize the icon as a lemming.
　I don't know whether your requests are adopted in its design, but I hope that he will keep your requests in mind to make the final image.

@cxxxr 
英語理解できてそうですね。

**Comment by Shinmera** [comment]
I've adapted the chosen design to a vector graphic image and created a set of colourings. Please have a look and tell me if there's anything you'd like changed.

You can conveniently view the current batch of icons here: https://shinmera.github.io/lem-icon/

**Comment by Shinmera** [comment]
As for making the design more Lemming-like: I'm afraid that I don't have any ideas myself on how to do that, but I'd be open to concrete ideas.

**Comment by t-cool** [comment]
@cxxxr 

I've adapted the chosen design to a vector graphic image and created a set of colourings. Please have a look and tell me if there's anything you'd like changed.
選択いただいたデザインをベクター形式に適応させて色付けをしました。案を見ていただいて、もし何か変更してほしい点があれば教えてください。

You can conveniently view the current batch of icons here: https://shinmera.github.io/lem-icon/
現状のアイコン一覧は、ここから閲覧できます: https://shinmera.github.io/lem-icon/

As for making the design more lemming-like: I'm afraid that I don't have any ideas myself on how to do that, but I'd be open to concrete suggestions.
よりデザインをレミングらしくする案について: 申し訳ないですが、どのように実現するかアイデアが思い浮かびませんでしたが、具体的な提案があればお聞きしたいと思っています。

**Comment by t-cool** [comment]
@Shinmera 

アイコンありがとうございます。
Thank you for making the icon for lem.

色の分け方は現状で満足です。
I like a set of colorings you suggested on your webpage.

変更してほしい点としては、下の手の出っ張りが口を大きく開けているように見えることです。なので、そこが口に見えないように変更してもらえればありがたいです。
What I'd like to change is the lower right part: It looks like a lemming opening its mouth wide.  So I'd like you to change it not to be seen as a mouth.

頭の輪郭と下の出っ張りに繋がる線が交わっているところをTの形にするか、
Whether it works or not, I have two ideas: The one is to change the point between its head and body like this. 
![https://drive.google.com/file/d/1rl3D0OJAIalNVbe5rYxfdW-2ayMuG7FM/view?usp=sharing](https://drive.google.com/file/d/1rl3D0OJAIalNVbe5rYxfdW-2ayMuG7FM/view?usp=sharing)

二枚目の画像の他三つのように出っ張り自体を無くすと解決できませんか？ 
The other one is to change the image like the images 2-4, which have no wings. 
![image](https://camo.githubusercontent.com/3c9ab5f061bf70a4bfe646d15fff6b81250c9b08/687474703a2f2f73747564696f2e74796d6f6f6e2e65752f6170692f73747564696f2f66696c653f69643d31333730)

それ以外により良い方法があればそれでお願いします。
If there is a better way, I'll leave it to you.

**Comment by Shinmera** [comment]
Please excuse my lack of response, I'm currently travelling in Japan on holidays and haven't had the time to work on your request yet. I will get to it once I'm back in Switzerland.

コミュニケーションの欠所についてすみません。さいきん日本で休みをしますから、働くは時間がありませんでした。スイスに帰ったのときはつづけます。

**Comment by t-cool** [comment]
@Shinmera 
Please enjoy your stay in Japan 👍

**Comment by cxxxr** [comment]
それで良さそうです
ありがとうございます

**Comment by Shinmera** [comment]
Do you want me to make some other colour versions of this version, or is this one alone fine?

**Comment by Shinmera** [comment]
はい。

**Comment by cxxxr** [comment]
paypalから指定のメールアドレスに送金しました。

**Comment by Shinmera** [comment]
お金を受け取りました。ありがとうございます！
最近気分が悪くなったから、アイコンのために時間がありませんでした。申し訳ありませんでした。
元気なるのときに新しいカラースキームをデザインします。

**Comment by cxxxr** [comment]
出来上がったのでこのissueは閉じます。
ありがとうございました。
