### ISSUE TITLE
[vi-mode] Typing i immediatly after Esc is regarded as `M-i`

### ISSUE THREAD

**Issue by utatatata** [cxxxr/lem#287]
e.g. after inputing '()'.

**Comment by utatatata** [comment]
I expect returning to normal mode, but it's not actually like that.

It seemed to be by design and conflicted with default key bindings.

Is there any solution?

**Comment by fukamachi** [comment]
> e.g. after inputing '()'.
> Is there any solution?

Use M-x paredit-mode!

**Comment by snmsts** [comment]
It's Japanese article about why it need timeout.
https://qiita.com/kefir_/items/415a30930a80b9b42adb#mintty%E3%81%AE%E6%8B%A1%E5%BC%B5%E3%83%A2%E3%83%BC%E3%83%897727%E3%81%B8%E3%81%AE%E5%AF%BE%E5%BF%9C

**Comment by henninltn** [comment]
Thanks, I understand the necessity of timeout.

I'll use PareaEdit.

**Comment by kenoss** [comment]
I guess we can close this issue.
