### ISSUE TITLE
入力用スレッドとメインループのウィンドウの描画が同時に起こった時に画面が乱れる

### ISSUE THREAD

**Issue by cxxxr** [cxxxr/lem#31]
入力部分で排他ロックしてるはずなのになんでだろう

**Comment by cxxxr** [comment]
7230bf514b83c1461f20777c6fe87356ea68edd3
とりあえずこれで乱れなくなった気がする

**Comment by KeenS** [comment]
描画は描画用スレッドを1つだけにするのを良くみますね。lemでいうメインスレッドの役割でしょうか。

**Comment by cxxxr** [comment]
そうしてるはずなんですがncursesの入力関数とぶつかるとおかしくなるみたいなんです

**Comment by cxxxr** [comment]
ncursesの入力関数ではなくlem側で管理してる入力用キューかもしれませんが

**Comment by cxxxr** [comment]
しばらく使ってるけど再現しないので直ったということにする
