### ISSUE TITLE
[paredit] Allow to slurp/barf/splice in a string literal

### ISSUE THREAD

**Issue by fukamachi** [cxxxr/lem#312]

**Comment by cxxxr** [comment]
@gos-k 口頭で似たようなことを聞いた気がしますが出来てませんか?

**Comment by fukamachi** [comment]
paredit-slurpは動いていなさそう

**Comment by gos-k** [comment]
slurp修正しました。
https://github.com/cxxxr/lem/commit/652ab5ce2ca66c56811e86e72e8e9467ef9f7686
