### ISSUE TITLE
lem-xcb support.

### ISSUE THREAD

**Issue by snmsts** [cxxxr/lem#329]
lem development is currently active so every frontend should have at least an active developer who follow the change to catch up the newest.
``lem-xcb`` is developed @stacksmith and seems current active committers are not using it daily.
We are planning to change api between backend frontend.
If no one is interested in supporting. we are planning to drop the support xcb.(by april/2019)

**Comment by stacksmith** [comment]
lem-xcb is an experiment, and needs a bit of work.  To be really useful it would need at least harfbuzz for proper shaping.  I do not have time to fix it so my suggestion is to drop it and use a more mature X front end.

**Comment by snmsts** [comment]
Got it. Thank you. hope you have more time to hack it.
