### ISSUE TITLE
OpenGL frontend?

### ISSUE THREAD

**Issue by terminal625** [cxxxr/lem#352]
If Lem had an OpenGL accelerated frontend it could seamlessly integrate graphics, similar to [McCLIM](https://common-lisp.net/project/mcclim/), [Dr Racket](https://racket-lang.org/), [Pharo](https://pharo.org/), or [3b](https://www.youtube.com/watch?v=DS_cwQJc8HY). It would be like the ncurses frontend except render directly to an OpenGL texture. [This GPU accelerated text-grid thing](https://github.com/terminal625/sucle/tree/master/application/subsystems/text-subsystem) might be able to substitute for ncurses for example. This would enable Lem to run a full Common Lisp IDE anywhere there is OpenGL, for example mobile or inside VR/AR or video games = profit. Finally, a Common Lisp VR game engine IDE you would never have to leave. What do you guys think?

**Comment by terminal625** [comment]
![lem-opengl](https://user-images.githubusercontent.com/14166099/49682605-11248300-fa85-11e8-9b47-404c480a3342.png)

I got lem to work with an OpenGL frontend, here's a picture and [here's the repo ](https://github.com/terminal625/lem-opengl)

**Comment by cxxxr** [comment]
Sounds good.
I want to merge if it works well.
