### ISSUE TITLE
Lem in quicklisp?

### ISSUE THREAD

**Issue by gmasching** [cxxxr/lem#359]
Can we have lem in quicklisp?

**Comment by snmsts** [comment]
would you like to register?

**Comment by pupcraft** [comment]
Yes, I would register it. But each ".asd" file needs `:author`, `:description`, and `:license`.

```
:author "SANO Masatoshi, cxxxr"
:license "MIT"
:description "????? system for lem: the editor for Common Lispers"
```
Is this good?

Also, Some ".asd" files say `;;don't edit` like [lem-mouse-sgr1006](https://github.com/cxxxr/lem/blob/master/contrib/mouse-sgr1006/lem-mouse-sgr1006.asd)

**Comment by snmsts** [comment]
ros project is not perfect and "don't edit" is to avoid breaking file by hand editing... actually you can edit. I feel I'm the second contributor and I don't need to be written in.

@cxxxr 何が質問されているかはわかると思うんだけど、どう思う？

**Comment by snmsts** [comment]
@pupcraft I'll edit at least some of asd's author/description.

**Comment by cxxxr** [comment]
@snmsts 
quicklispへの登録はやってもいいと思います。
authorはシステム毎に一番変更量が多い人の名前が良い気がしますが
ディレクトリ毎移動しているのでそこは注意したほうがいいですね。

**Comment by snmsts** [comment]
@cxxxr your name in author field still "cxxxr"?

**Comment by cxxxr** [comment]
@snmsts yes

**Comment by snmsts** [comment]
https://github.com/cxxxr/lem/commit/8510a9a6f7dbf90b56761d34a35210f8e3aa5f9c

**Comment by phoe** [comment]
> The "author" written there could be the person who wrote the most in the system.

You can list all authors there, no problem.

**Comment by snmsts** [comment]
@phoe  Thank you.

> You can list all authors there, no problem.

I believe we know...

**Comment by t-sin** [comment]
Thanks for credit! I think it's OK.

**Comment by snmsts** [comment]
simple description todo.

- [ ] ./contrib/tetris/lem-tetris.asd
- [ ] ./contrib/man/lem-man.asd
- [ ] ./contrib/modeline-battery/lem-modeline-battery.asd
- [ ] ./contrib/fbar/lem-fbar.asd
- [ ] ./contrib/bracket-paren-mode/lem-bracket-paren-mode.asd
- [ ] ./contrib/select-popup/lem-select-popup.asd
- [ ] ./contrib/mouse-sgr1006/lem-mouse-sgr1006.asd
- [ ] ./contrib/migemo/lem-migemo.asd
- [ ] ./contrib/lem-contrib.asd
- [ ] ./contrib/version-up/lem-version-up.asd
- [ ] ./contrib/trailing-spaces/lem-trailing-spaces.asd
- [ ] ./contrib/weaver/weaver.asd
- [ ] ./contrib/google-translate/lem-google-translate.asd
- [ ] ./lib/core/lem-core.asd
- [ ] ./lib/base/lem-base.asd
- [ ] ./lib/setlocale/lem-setlocale.asd
- [ ] ./lib/encodings/encodings-table/lem-encodings-table.asd
- [ ] ./lib/encodings/lem-encodings.asd
- [ ] ./lib/lsp-mode/lem-lsp-mode.asd
- [ ] ./lib/process/lem-process.asd
- [ ] ./lib/lisp-syntax/lem-lisp-syntax.asd
- [ ] ./frontends/ncurses/lem-ncurses.asd
- [ ] ./frontends/jsonrpc/lem-jsonrpc.asd
- [ ] ./frontends/xcb/lem-xcb.asd
- [ ] ./frontends/capi/lem-capi.asd
- [ ] ./frontends/pdcurses/lem-pdcurses.asd
- [ ] ./frontends/electron/webview/lem-webview.asd
- [ ] ./frontends/electron/lem-electron-backend/lem-electron-backend.asd
- [ ] ./frontends/electron/markdown-preview/lem-markdown.asd
- [ ] ./lem.asd
- [ ] ./modes/html-mode/lem-html-mode.asd
- [ ] ./modes/calc-mode/lem-calc-mode.asd
- [ ] ./modes/rust-mode/lem-rust-mode.asd
- [ ] ./modes/html-mode--/lem-html-mode.asd
- [ ] ./modes/css-mode/lem-css-mode.asd
- [ ] ./modes/python-mode/lem-python-mode.asd
- [ ] ./modes/scheme-mode/lem-scheme-mode.asd
- [ ] ./modes/markdown-mode/lem-markdown-mode.asd
- [ ] ./modes/xml-mode/lem-xml-mode.asd
- [ ] ./modes/vi-mode/lem-vi-mode.asd
- [ ] ./modes/lisp-mode/lem-lisp-mode.asd
- [ ] ./modes/nim-mode/lem-nim-mode.asd
- [ ] ./modes/selection-mode/lem-selection-mode.asd
- [ ] ./modes/paredit-mode/lem-paredit-mode.asd
- [ ] ./modes/diff-mode/lem-diff-mode.asd
- [ ] ./modes/js-mode/lem-js-mode.asd
- [ ] ./modes/go-mode/lem-go-mode.asd
- [ ] ./modes/c-mode/lem-c-mode.asd
- [ ] ./modes/yaml-mode/lem-yaml-mode.asd
- [ ] ./modes/posix-shell-mode/lem-posix-shell-mode.asd

**Comment by pupcraft** [comment]
@snmsts do you help adding descriptions? It seems like a lot work and I can try to help if you want

**Comment by snmsts** [comment]
@pupcraft  Yes. Any help would be welcomed.

quicklisp registration todo.
- [ ] trivial-battery
- [ ] sn.man
- [ ] cl-migemo
- [ ] async-process

**Comment by pupcraft** [comment]
trivial battery is already in quicklisp: [http://quickdocs.org/trivial-battery/](http://quickdocs.org/trivial-battery/)

**Comment by pupcraft** [comment]
Actually I change my mind, Lem doesn't have to be on quicklisp, sorry for the trouble @snmsts 
I'll just use [https://github.com/snmsts/github-install](https://github.com/snmsts/github-install)
You can delete the `edit-asd` branch
Thank you for helping!!

**Comment by phoe** [comment]
I think it would nonetheless be useful for the Lisp community in general if lem is available on Quicklisp - QL is much more popular than github-install.

If you don't have the time/energy for doing this and if need any support with making lem available, please let us know - I think there are people who can support you with all the needed work.

**Comment by nz-tcoder** [comment]
> [8510a9a](https://github.com/cxxxr/lem/commit/8510a9a6f7dbf90b56761d34a35210f8e3aa5f9c) 

@snmsts thanks! I'm OK.

**Comment by snmsts** [comment]
what happend @pupcraft  ?

**Comment by pupcraft** [comment]
Why put lem on quicklisp?

**Comment by snmsts** [comment]
I don't know...sometime I feel software which are not on ql is not exist for common lisp society.
publicity for me?

**Comment by phoe** [comment]
> Registering on quicklisp is hard

What exactly is? I don't understand the issue. All ASD systems need to have basic information filled into them, and the package has to build without errors - these are the only two real requirements.

**Comment by pupcraft** [comment]
@phoe registering on quicklisp takes a relatively long time, and requires coordination. So maybe the best way to distribute software is to start with github-install or qlot or roswell first, and switch when quicklisp updates.

**Comment by ryukinix** [comment]
I would like to see this happening.

**Comment by pupcraft** [comment]
@ryukinix here it is pending for ultralisp: https://ultralisp.org/projects/cxxxr/lem

quicksys looks pretty good. I wonder how the lisp ecosystem will evolve

**Comment by pupcraft** [comment]
sorry, accidentally closed and reopened

**Comment by ryukinix** [comment]
Good to see that! @pupcraft 

> quicksys looks pretty good. I wonder how the lisp ecosystem will evolve

Nice to hear it, I'm waiting Xach approval to be on quicklisp, they said to me that the project it's ok but seems that quicklisp is not available in the environment of project building... which is a problem for a project like quicksys. You can find more info [here].

[here]: https://github.com/quicklisp/quicklisp-projects/issues/1654

**Comment by pupcraft** [comment]
https://ultralisp.org/projects/cxxxr/lem is now live!

@ryukinix sounds like a circular problem, having to build quicklisp to be on quicklisp but quicklisp not being available. Do you think ultralisp is the best dist to use in the meantime?

**Comment by pupcraft** [comment]
unfortunately ultralisp does not seem to recognize nested asd files. 
so https://ultralisp.org/projects/cxxxr/lem is not live...

**Comment by svetlyak40wt** [comment]
I'm doing my best to make Ultralisp is the best place for hosting Common Lisp libraries, guys!

And any help is very appreciated ;-)

The [biggest problem](https://github.com/ultralisp/ultralisp/issues/42) right now is that site sometimes hangs because it uses [lfarm](http://quickdocs.org/lfarm/) to delegate checking of the new updated into a separate docker container, and lfarm seems does not close sockets when it loses connection to a worker. And during the time, server eats a limit of available file descriptors and hangs.

However, this problem does not affect already built distribution, because they are served directly from Amazon S3.

**Comment by phoe** [comment]
> and lfarm seems does not close sockets when it loses connection to a worker.

I do not see an open bugticket on https://github.com/lmj/lfarm/issues related to this. Have you made one?

**Comment by svetlyak40wt** [comment]
@pupcraft you are correct about nested asd files. Their support was turned off intentionally, because some libraries have broken or test nested asd files. Something like skeletons with template placeholders, or example systems. That is why I decided to not parse them by default.

But I want to add support for an explicit list of asd files as a per-project setting. Feel free to create such an issue and help with development. Or just wait while somebody else will implement this feature.

**Comment by jessymilare** [comment]
I just copied lem directory in `local-projects/`. It loads and builds nicely. I don't understand why can't Quicklisp just pack it. I tried Roswell and didn't like it, I honestly prefer Quicklisp only.

**Comment by ryukinix** [comment]
That's problems of Common Lisp package distribution it's a quite bad. There is a giant efforts of Xach and ASDF authors (that's guy are heros!), but I hope one day we can kill all that problems as @svetlyak40wt are trying a really nice effort to bring to us a less painful way to publish/deliver/control dependencies and projects. 

We need really to unify forces for the greater good.

**Comment by pupcraft** [comment]
@ryukinix how do you think we should unify forces?

**Comment by ryukinix** [comment]
Hi @pupcraft, I'm glad that you ask.

In my view, i think we need freedom to distribute software without peer-review, as first problem to solve. That's the way modern software development works. That thing of a centralized Xach-review approval it's not a good thing. 

The second problem it's make it easy to install, which Roswell are making a good job on this. 

About Quicklisp repository, I prefer the more liberal @svetlyak40wt approach by giving the freedom of user to publish your own software with fast releases when he wants without need of approval.

The way we can unify forces I'll would suggest it's help Alexander to make ultralisp better and more easy to install greatly, as well roswell. Maybe a automation script ignoring the steps to deal with quicklisp stuff and just use as lib? Something like that.

Quicklisp it's great as tool, the main problem and it's publishing software as we see here. Unfortunately ultralisp have your own problems too and for that reason we still cannot publish `lem` on there (yet).

But we, as Common Lisp Community, can do a great thing.

In my view projects like Roswell and Ultralisp are awesome ideas and deserves more attention.

**Comment by jessymilare** [comment]
> 
> In my view projects like Roswell and Ultralisp are awesome ideas and deserves more attention.

Totally agree. I used to use clbuild before Quicklisp was available and I missed the ability to simply add repos to my system list. What I didn't like about Roswell is it's somewhat invasive. As I used it, it downloaded SBCL and Quicklisp, even though I already had both in my system. It should, by default, look for or at least ask. Running 'ros -h' didn't tell me how to do that. I tried it anyway, but as I tried to copy my quicklisp into .ros, it broke. I didn't find anything about using my own Quicklisp and SBCL with Roswell, then I gave up.

The system manager needs to adapt itself to what I already have installed, not the other way around. For newbies, on the other hand, or people who are willing to reconfigure their on environments, Roswell seems very good.

**Comment by phoe** [comment]
> I don't understand why can't Quicklisp just pack it.

@jessymilare Seems like https://github.com/quicklisp/quicklisp-projects/issues/1624 has an answer - Quicklisp cannot build projects that themselves depend on Quicklisp, and it seems that lem has such dependencies somewhere.

**Comment by snmsts** [comment]
Invasive...sad to hear. I support the idea to install lem without roswell. But could you stop negative comment on my product?
Do you need to say that? for what purpose?
I think "it would be nice if I can install lem without roswell" is enough.

thanks.

**Comment by jessymilare** [comment]
I had no intention to offend anyone. I apologize if it sounded like that. My only purpose was to point to one particular limitation of Roswell IMO. You might agree with me or not, change it or not, that is up to you.

**Comment by ryukinix** [comment]
> > I don't understand why can't Quicklisp just pack it.
> 
> @jessymilare Seems like [quicklisp/quicklisp-projects#1624](https://github.com/quicklisp/quicklisp-projects/issues/1624) has an answer - Quicklisp cannot build projects that themselves depend on Quicklisp, and it seems that lem has such dependencies somewhere.


That is worse. I think we can't have hope on that, the first issue about that has 7 years. https://github.com/quicklisp/quicklisp-projects/issues/425
I proposed quicksys as I said earlier to make easier to deal with another distributions, but 7 years... I don't if Xach really cares about this specific problem or it's a so hard/core problem that need to re-write the whole quicklisp (?)

**Comment by jessymilare** [comment]
> > > I don't understand why can't Quicklisp just pack it.
> > 
> > 
> > @jessymilare Seems like [quicklisp/quicklisp-projects#1624](https://github.com/quicklisp/quicklisp-projects/issues/1624) has an answer - Quicklisp cannot build projects that themselves depend on Quicklisp, and it seems that lem has such dependencies somewhere.
> 
> That is worse. I think we can't have hope on that, the first issue about that has 7 years. [quicklisp/quicklisp-projects#425](https://github.com/quicklisp/quicklisp-projects/issues/425)
> I proposed quicksys as I said earlier to make easier to deal with another distributions, but 7 years... I don't know if Xach really cares about this specific problem enough or it's a so hard/core problem that need to re-write the whole quicklisp (?)

It shouldn't be hard to remove the dependency on `quicklisp` and dynamically test for its presence at run time. That should be better in any case. `fgrep -ri "quicklisp"` shows only 19 occurrences in source code.

**Comment by phoe** [comment]
Also grep for `ql`.

But yes, depending on everything at runtime should be possible - it is possible to use `uiop:symbol-call` instead, for example.

**Comment by jessymilare** [comment]
Okay, first attempt. Comments are appreciated ^_^

https://github.com/cxxxr/lem/pull/400#issue-290864601

**Comment by phoe** [comment]
Thank you for making the PR! Commented on the code.

**Comment by phoe** [comment]
OK - Xach was able to perform compilation. http://report.quicklisp.org/2019-06-25/failure-report/lem.html are the errors that lem has generated as it was being built.

**Comment by jessymilare** [comment]
> OK - Xach was able to perform compilation. http://report.quicklisp.org/2019-06-25/failure-report/lem.html are the errors that lem has generated as it was being built.

About lem-xcb, I was told it wasn't supported anymore. If that is the case, maybe it's time to get rid of it. I intend to create a LTK frontend, which I believe will be more stable and maintainable, not sure when I'll have time, though.

I fixed a few typos and system dependencies. Many of the failures happend because the system definition lacks dependency on `lem-core`. However, there is a "don't edit" comment above the `defsystem` form of these systems, so I guess they are auto-generated and I didn't edit them. I might check that later.

[](https://github.com/cxxxr/lem/pull/401)

**Comment by snmsts** [comment]
I'll drop xcb.
@jessymilare which system would you like to edit?

**Comment by jessymilare** [comment]
> I'll drop xcb.
> @jessymilare which system would you like to edit?

All systems that reported `The name "LEM" does not designate any package.` The fix is to add "lem-core" in `:depends-on`. That means all contrib systems plus `lem-setlocale`, `lem-selection-mode` and `lem-calc-mode`.

**Comment by snmsts** [comment]
@jessymilare I guess I'm done.

**Comment by phoe** [comment]
@snmsts Let Xach know in the issue on quicklisp-projects - he'll redo the build and see if everything compiles now.

**Comment by jessymilare** [comment]
> @jessymilare I guess I'm done.

@snmsts Is any of the `.asd` files auto-generated? If not, there is no reason for the "don't edit" comment in the first line and the problem is very simple to solve.

**Comment by jessymilare** [comment]
By the way, IMHO, if a file is auto-generated, it shouldn't be source. That makes the project less maintainable and more confusing.

**Comment by gmasching** [comment]
This seems to be moving along quite slowly, so I'm forking lem to put on quicklisp. It will be called "minilem" and will remove all the extra modes and contrib files and backends, leaving only the base text editor.

**Comment by gmasching** [comment]
If anyone is interested, [its here](https://github.com/gmasching/minilem)

**Comment by svetlyak40wt** [comment]
@gmasching why do you want to have Lem in Quicklisp?

IMHO it is better to work on packaging for OSX, Ubuntu, etc.

**Comment by gmasching** [comment]
Because it's extremely simple to distribute lisp code that way. Just one function call and you have lem set up. This is important if you want new users. 
I'd like to use ultralisp but the `.asd` files have to be placed in the root directory, and that is a lot of refactoring. I'd be happy to help out solve this problem.

**Comment by phoe** [comment]
> and that is a lot of refactoring

AFAIK you can move all ASD files to the main directory and then add `:pathname "foo/bar/"` to each of them for the new source location to be recognized.

Nonetheless, you shouldn't need to do that - Ultralisp should be able to scan the repository's structure and discover ASD systems even in nested directories, since ASDF already does that on its own.

**Comment by gmasching** [comment]
@phoe wow really? That would have made this process so much easier. Thank you for clarifying. I guess it wasn't a problem after all...

**Comment by phoe** [comment]
See https://github.com/mfiano/pngload-fast/blob/master/pngload-fast.asd for example.

```lisp
(asdf:defsystem #:pngload-fast
  ...
  :pathname "src"
  ...
  ((:file "package") ;; refers fo src/package.lisp
   ...
   ))
```

**Comment by svetlyak40wt** [comment]
Ultralisp should process nested asd files, but it does not. It was turned off because some projects have broken nested asd files. Either they are examples or some tests or third party libraries bundled into the repository.

I'm aware of this problem and hope somebody will help to add a project-level setting to set up an ignore list. After that, the loading of the nested asd files can be enabled by default.
