### ISSUE TITLE
find-definitions point to travis user folder

### ISSUE THREAD

**Issue by osktyn** [cxxxr/lem#361]
Calling `find-definitions` on any built-in symbol produced error starting with `directory does not exists: /home/travis/build/roswell/sbcl_bin/sbcl/src/code/`. Lem updated today. I can post full trace if needed. 

Thank you for making lem I really like it.

**Comment by cxxxr** [comment]
Did you install sbcl source code?
Please try the following command.

`$ ros install sbcl --without-install`

**Comment by osktyn** [comment]
I did, but it still points to that same user folder `/home/travis/...` that doesn't exists on my system. 

Shouldn't it point toward some subdirectory of `/home/my-username/.roswell/` ?

**Comment by cxxxr** [comment]
I don't know the cause.

It may be a problem of roswell.

how is it? @snmsts

**Comment by snmsts** [comment]
hmmm... how did you install lem? @osktyn

**Comment by cxxxr** [comment]
Is it the same if I delete the cache?

`$ rm -rf $HOME/.cache/common-lisp/`

**Comment by cxxxr** [comment]
It reproduced under the following environment.
ubuntu 18.04
sbcl-1.4.16-x86-64-linux (binary)

```
$ sbcl --noinform
* (translate-logical-pathname #P"SYS:SRC;CODE;PRED.LISP")
=> #p"/home/christophe/src/sbcl-release-dir-20190126-dssp1Ufgu/sbcl-1.4.16/src/code/pred.lisp"
```

To solve, please build in your own environment. (.e.g `$ ros install sbcl/1.4.16`)

**Comment by sakurawald** [comment]
> Did you install sbcl source code? Please try the following command.
> 
> `$ ros install sbcl --without-install`

This solution does solve my situation: the goto definition popup the error `directory does not exists: /tmp/sbcl/src/code`.

It would be fine if the command `ros install sbcl --without-install` is written in the manual of lem editor.
