### ISSUE TITLE
Add a short instruction how to hack on Lem itself

### ISSUE THREAD

**Issue by svetlyak40wt** [cxxxr/lem#367]
For example, is there a way to connect to Lem using SLIME and change it while it is running?
Or maybe it is built in and I can somehow edit Lem's sources, evaluate them and change editor's behaviour on the fly?

I believe such a section in the README could lead to a bigger number of contributions because right now it is completely unknown how to get started with Lem development.

**Comment by cxxxr** [comment]
Thank you for your advice.
I added what I came up to the wiki.

**Comment by svetlyak40wt** [comment]
Great! If only I was able to translate it!

**Comment by svetlyak40wt** [comment]
Closed by adding wiki page:

https://github.com/cxxxr/lem/wiki/How-to-hack-on-lem-itself
