### ISSUE TITLE
Key not found: Escape

### ISSUE THREAD

**Issue by matteoeghirotta** [cxxxr/lem#372]
Hi, just tried lem with the ncurses frontend on a debian linux box, using both urxvt, st and gnome-terminal terminals.
 Not sure about this issue, since nobody seems to notice the following problem: 

every time I insert a key sequence containing escape, or just typing the escape character results in a message: 
Key not found: Escape 

Also Ctrl- and others, which should be translated as (common lisp characters): #\Esc #[ #\1 #; #\5 #\D  fails, printing just #[ #\1 #; #\5  #\D (escape char seem to be ignored) 
Am I the only one experimenting this issue?
--

**Comment by snmsts** [comment]
It comes from timeout after escape is so severe (100ms) if you type `x` just after escape you can see it taken as `M-x` unless it taken as single escape key and there's no binding for the key.

**Comment by matteoeghirotta** [comment]
So no hope to have ctrl-right working? I see this binding defined in your source code. Is it possible to overcome this timeout issue, as done in  e.g emacs?

**Comment by snmsts** [comment]
ok ctrl-right would work.

**Comment by matteoeghirotta** [comment]
Many thanks for taking time to face this issue. Unfortunately even after updating lem (ros update lem) 
typing C-Right (or other arrow keys) still just prints out some terminal code (C-right prints ";5C"), after I bound it in ~/.lem/init.lisp, as below
(define-key *global-keymap* "C-Right" 'window-move-right)

This seem to be a common issue in the terminal, since I also found problems using linedit, where typing C-<arrows> would freeze the repl. I managed to send the developers a pull request fixing the issue,  https://github.com/sharplispers/linedit/pull/4

**Comment by snmsts** [comment]
https://github.com/cxxxr/lem/commit/7abe3684859c5e3111e3323dd7851b29a4927aac fixed?

**Comment by matteoeghirotta** [comment]
Perfect thank you so much
