### ISSUE TITLE
READMEの書き直しとか一通りの使い方、ドキュメントなど

### ISSUE THREAD

**Issue by cxxxr** [cxxxr/lem#38]

**Comment by fukamachi** [comment]
ユーザがRoswellを使っている場合はインストールがとても楽になっているようです。

```
$ ros install cxxxr/lem
$ lem
```

**Comment by cxxxr** [comment]
それはreadmeに書いておいたほうが良さそうですね

roswellが入ってることを前提にしていいのかはよくわからない

**Comment by snmsts** [comment]
> roswellが入ってることを前提にしていいのかはよくわからない

*nixでの動作検証等々考えるとroswell無しのインストールが併記されている方が良いと思います。

linux環境だけならそろそろ使用が奨励されても良いのでは…とは思っていますが。

**Comment by cxxxr** [comment]
大体の人はasdfやquicklisp周りの事は知ってる筈なので  
専用のやり方を用意していない限り、説明を見るまでもないかもしれません…

**Comment by droidkita** [comment]
はじめまして、
Lisp入門書に記載がないasdfやquicklisp周りの事が解らず、
roswell使ってもインストール出来てない私の様なLispド素人にも
判るように教えて頂けると助かります。

**Comment by cxxxr** [comment]
使う人がいるかはわかりませんが、とりあえず日本語のドキュメントを用意していき、
英語も後から付け足せる形でぼちぼち用意していきます

**Comment by cxxxr** [comment]
古くなったのでとりあえず閉じます
