### ISSUE TITLE
Adding another sample config example

### ISSUE THREAD

**Issue by Fedreg** [cxxxr/lem#383]
Hi, great project! Thanks to all for working on this!

I was very excited to try Lem but the example config didn't give me a very clear idea of how to personalize the editor.  After looking at the code and config examples I was eventually able to set up a few things.  Here is a basic version.  Adding it here in case it is helpful to anyone.  Can add as another example in README if you'd like.   Thanks again!!

https://github.com/Fedreg/.lem/blob/master/init.lisp

**Comment by cxxxr** [comment]
Thank you.
Please contribute to the README,md and [lemrc-example](https://github.com/cxxxr/lem/blob/master/lemrc-example) if you are OK.

**Comment by Fedreg** [comment]
PR #384 Just added a link to the README, didn't want to modify the official `lemrc-example`.  Merge if you think helpful.  No worries if not.  Thx again!!
