### ISSUE TITLE
McCLIM frontend?

### ISSUE THREAD

**Issue by ebrasca** [cxxxr/lem#402]
Do you support or plan to support McCLIM frontend?

**Comment by snmsts** [comment]
I haven't hard of practical plan from active members..

**Comment by ebrasca** [comment]
I think if lem have McCLIM frontend , it is probably going to work in Mezzano.
Do you think it is hard to make McCLIM frontend?

**Comment by jessymilare** [comment]
I intend to work on an LTK frontend. I honestly believe McCLIM is somewhat heavy.

**Comment by ebrasca** [comment]
I don't think LTK is going to work in Mezzano.
Mezzano is an operating system written in Common Lisp.
https://github.com/froggey/Mezzano

**Comment by jessymilare** [comment]
> I don't think LTK is going to work in Mezzano.
> Mezzano is an operating system written in Common Lisp.
> https://github.com/froggey/Mezzano

Oh, forgive me, I had forgotten that. Well, I've just downloaded McCLIM again and I think it is too much. However, LTK is simple enough, if one ports it (or part of it) to McCLIM or implement it directly in Mezzano, we can have a common portable frontend.

**Comment by ebrasca** [comment]
I don't undestand what do you mean with "McCLIM is somewhat heavy".
too much of what? LOC?

**Comment by snmsts** [comment]
@ebrasca I think @jessymilare still don't recall it's Mezzano. There's no tcl/tk to rely on.
When it comes to frontend, our conversation would stuck like the bike shed effect.
Man power is the problem and lem doesn't have any problem having mcclim frontend if someone volunteer to maintain it.
The answer for the question is still no.

**Comment by jessymilare** [comment]
> @ebrasca I think @jessymilare still don't recall it's Mezzano. There's no tcl/tk to rely on.

LTK is Lisp. It's not like other libraries that practically incorporate TCL in CL. In LTK, widgets are CLOS instances controlled by CLOS methods, callbacks are Lisp functions. One could implement these instances and methods onto another GUI library.

**Comment by jessymilare** [comment]
> I don't undestand what do you mean with "McCLIM is somewhat heavy".
> too much of what? LOC?

LOC, size, time to load. One simple test in Lem REPL, which already includes some libraries I use.

```
cl-user> (gc)
nil
cl-user> (sb-vm:memory-usage)
;;; [... Lots of output ...]
Summary total:
    71,780,512 bytes, 1,144,108 objects.
; No value
cl-user>(time (quickload :ltk)) 
To load "ltk":
  Load 1 ASDF system:
    ltk
; Loading "ltk"

Evaluation took:
  0.243 seconds of real time
  0.318893 seconds of total run time (0.315807 user, 0.003086 system)
  131.28% CPU
  26 forms interpreted
  1 lambda converted
  584,267,856 processor cycles
  10,448,960 bytes consed

(:ltk)
cl-user> (gc) 
nil
cl-user> (sb-vm:memory-usage)
;;; [...]
Summary total:
    77,249,584 bytes, 1,251,250 objects.
; No value
cl-user> (time (quickload :mcclim)) 
To load "mcclim":
  Load 1 ASDF system:
    mcclim
; Loading "mcclim"
.........
Evaluation took:
  4.437 seconds of real time
  4.916961 seconds of total run time (4.774580 user, 0.142381 system)
  [ Run times consist of 0.172 seconds GC time, and 4.745 seconds non-GC time. ]
  110.82% CPU
  923 forms interpreted
  1,875 lambdas converted
  10,648,520,472 processor cycles
  351,188,512 bytes consed

(:mcclim)
cl-user> (sb-vm:memory-usage)
;;; [...]
Summary total:
    138,529,424 bytes, 2,263,529 objects.
; No value
```

Mezzano already includes and loads McCLIM by default, it makes perfect sense to use it, of course.

**Comment by snmsts** [comment]
question answered

**Comment by t-sin** [comment]
@jessymilare I think the answer is this...:

Ltk is a Tcl/Tk wapper library written in Common Lisp (see Ltk manual). So it does not run on Mezzano...
