### ISSUE TITLE
Lem hangs after M-x start-lisp-repl

### ISSUE THREAD

**Issue by svetlyak40wt** [cxxxr/lem#411]
I'm using latest OS version, built from sources: lem 1.5-25c95fbc (X86-64)

Same problem with Lem, installed with `ros install cxxxr/lem`

**Comment by svetlyak40wt** [comment]
Interesting, tried to checkout older commits, and it does not work either.

**Comment by svetlyak40wt** [comment]
I've checked 1.5-25c95fbc on my other laptop, and it does work!

Interesting, why does it hang on one MacBook and doesn't on another?

**Comment by cxxxr** [comment]
I have never reproduced it.
I think it's probably due to usocket or something, not a lem issue.

**Comment by svetlyak40wt** [comment]
@cxxxr do you have an idea how to debug it?

**Comment by cxxxr** [comment]
What about print debug?
Provided the function `pdebug`

**Comment by svetlyak40wt** [comment]
How should I use it?

I found that Lem hangs even when I just change current buffer's to `lisp-mode`.

OSX's activity monitory shows that after I call `lisp-mode`, Lem opens a port like `localhost:54361` and connects to it `localhost:51384->localhost:54361`.

**Comment by cxxxr** [comment]
How about this
https://github.com/cxxxr/lem/compare/issue-411-print-debug

**Comment by svetlyak40wt** [comment]
Thank you!

1. I've modified a lem a little bit such way that it does not call `new-connection`.
2. Started a separate Lisp process with an Emacs and SLY.
3. Loaded Lem's sources
4. And tried to call new-connection.
5. It hangs on `read-return-message` call after the (emacs-rex-string connection `(swank:init-presentations)")` on line: https://github.com/cxxxr/lem/blob/35e915a561d8faccf3802cee5dd8d4ff86b1def9/modes/lisp-mode/swank-protocol.lisp#L208

Probably using some logging library across all Lem's codebase will make debugging much easier. How about integrating a [log4cl](http://quickdocs.org/log4cl/)?

**Comment by svetlyak40wt** [comment]
Also, there is no timeout in `read-return-message` itself:

```lisp
(defun read-return-message (connection)
  "Read only ':return' message. Other messages such as ':indentation-update' are dropped."
  (loop :for waiting := (message-waiting-p connection :timeout 5)
        :with info
        :do (unless waiting (return nil))
            (setf info (read-message connection))
            (when (eq (car info) :return)
              (return info))))
```

that is why Lem hangs instead of giving some error like "Unable to setup SLIME connection.

**Comment by Hamayama** [comment]
Hello.

I debugged this part before.
- https://github.com/cxxxr/lem/pull/436 [lisp-mode] Update swank protocol read message function
- https://github.com/cxxxr/lem/pull/393 Improve slime connection on Windows v3
- https://github.com/cxxxr/lem/pull/385 Improve slime connection on Windows

Sorry, I have only windows pc.

I used Wireshark-Portable and Npcap.
https://www.wireshark.org/download.html
https://nmap.org/npcap/

Npcap enabled to capture TCP packets only one pc.
(select Npcap Loopback Adapter)
(But, it seems for windows only, sorry I don't know other OS ...)

I set Wireshark's filter as follows.
 tcp and ip.addr == 127.0.0.1

![wshark](https://user-images.githubusercontent.com/4497079/69221306-46ed4980-0bba-11ea-8297-b3303d780fc1.png)

**Comment by svetlyak40wt** [comment]
I found the problem cause.

It fixed in this pull request: https://github.com/cxxxr/lem/pull/457

BTW, these changes were highly useful for discovering the bug: https://github.com/cxxxr/lem/pull/456 please review them.

**Comment by svetlyak40wt** [comment]
This issue was fixed by pull https://github.com/cxxxr/lem/pull/457
