### ISSUE TITLE
Guix package (or Lem without Roswell)

### ISSUE THREAD

**Issue by Ambrevar** [cxxxr/lem#412]
I'd like to package Lem for [Guix](https://guix.gnu.org).
Roswell is not very convenient to use for building packages (at least with Guix): is it somehow possible to build Lem without Roswell?

**Comment by cxxxr** [comment]
Yes. Please refer to lem.asd and build.lisp.

**Comment by Ambrevar** [comment]
Thanks.
Note that I had to add

```
(ql:quickload :roswell)
```

to build.lisp and then run

```
> sbcl --load build.lisp
This is SBCL 1.5.5, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "lem-ncurses":
  Load 1 ASDF system:
    lem-ncurses
; Loading "lem-ncurses"
..........
To load "roswell":
  Load 1 ASDF system:
    roswell
; Loading "roswell"
/gnu/store/q19l04vd2za80mk1845pz7r8cz29qk43-bash-minimal-4.4.23/bin/sh: NIL: command not found
.
[undoing binding stack and other enclosing state... done]
[performing final GC... done]
[defragmenting immobile space... (fin,inst,fdefn,code,sym)=1812+1270+27569+28931+27472... done]
[saving current Lisp image into lem-ncurses-NIL-NIL:
writing 0 bytes from the read-only space at 0x50000000
compressed 0 bytes into 8 at level -1
writing 432 bytes from the static space at 0x50100000
compressed 32768 bytes into 261 at level -1
writing 49152000 bytes from the dynamic space at 0x1000000000
compressed 49152000 bytes into 11400556 at level -1
writing 1507328 bytes from the immobile space at 0x50300000
compressed 1507328 bytes into 414256 at level -1
writing 18360576 bytes from the immobile space at 0x52100000
compressed 18382848 bytes into 5723024 at level -1
done]
```

It works!

Question: What's up with the lines

--8<---------------cut here---------------start------------->8---
/gnu/store/q19l04vd2za80mk1845pz7r8cz29qk43-bash-minimal-4.4.23/bin/sh: NIL: command not found
...
[saving current Lisp image into lem-ncurses-NIL-NIL:
--8<---------------cut here---------------end--------------->8---

Seems harmless, but I get a weird file name ;)

**Comment by Ambrevar** [comment]
I've figured something out: when the executable roswell is not running,
the ROS_OPT environment variable is not exported, which leads in all
`roswell:opt`-based functions to fail.

A fix would be to avoid using `roswell.util:uname(-m)` here, and use
their UIOP counterparts (`(uiop:operating-system)` and
`(uiop:architecture)`) or to fix `*ros-opts*` for this file only:

--8<---------------cut here---------------start------------->8---
(setf roswell::*ros-opts*
      `(("uname" ,(uiop:run-program "uname" :output '(:string :stripped t)))
        ("uname-m" ,(uiop:run-program '("uname" "-m") :output '(:string :stripped t)))))
--8<---------------cut here---------------end--------------->8---

(Before saving to the executable.)

**Comment by jgarte** [comment]
@Ambrevar 

https://github.com/lem-project/lem/discussions/1554
