### ISSUE TITLE
language server対応

### ISSUE THREAD

**Issue by snmsts** [cxxxr/lem#43]
common lispでswankの代替物として、language server(の拡張)を実装する事を考えています。
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

興味ありませんか?

**Comment by cxxxr** [comment]
興味あります
まだ実際に動くものは無いようですがいつ頃になるんでしょう

**Comment by snmsts** [comment]
年内という煽りを受けていますが未定です。
http://clfreaks.org/post/154877775924/13-throw-away-your-emacs

slackで相談をしているのですがそちらも興味ないですか?
日本語です。

**Comment by cxxxr** [comment]
slack興味ありますね
チャットツールは使ったことがなくて今アカウント作り始めたばかりですが

**Comment by snmsts** [comment]
メールで招待するのでメール下さい snmsts@gmail.com

**Comment by cxxxr** [comment]
このissueそろそろ閉じますね

**Comment by snmsts** [comment]
終わってましたね…
