### ISSUE TITLE
lisp-compile-defun does not work for connection to CCL when there is active "self connection"

### ISSUE THREAD

**Issue by svetlyak40wt** [cxxxr/lem#460]
I'm using Lem from 7fb9c99d9f465efa31de4fcb1fb7615f937de541 commit (latest for today).

The problem is that when I'm connecting from the LEM to a separate Lisp process, C-c C-c evals code in a wrong connection.

NOTE: This problem is not possible to reproduce, if outer process is SBCL. Bug exists only on CCL.

#### Start a separate CCL lisp process with a swank server

(here I'm starting latest 1.12 build because 1.11 does not work on a recent OSX)

```
rlwrap ./dx86cl64 -e '(load "/Users/art/quicklisp/setup.lisp")' -e '(ql:quickload :swank)'
```

```
(swank:create-server :port 5009  :style :spawn :dont-close t)
```

#### Start the Lem

And connect to the `5009` port using a `slime-connect` command.

Then call `slime-self-connect`.

#### Switch back to ccl-bin

Call `lisp-connection-list`, select the second line with CCL interpreter and hit Return (Enter).

```
  hostname  port  pid   name version                                    command
* 127.0.0.1 51499 SELF  sbcl 1.5.8                                      NIL
  127.0.0.1 5009  52489 ccl  Version 1.12-dev (v1.12-dev.5) DarwinX8664 NIL
```

#### Create a foo.lisp

With following content:

```
(defparameter *foo* "bar")
```

#### Eval the line

Hit `C-c C-c` on this line.

#### Check the variable in the REPL

Switch back to the REPL and enter:

```
*foo*
```

You should receive a 

```
Unbound variable: *FOO*
```

**Comment by svetlyak40wt** [comment]
Does anybody have an idea why this error occurs only when connecting to the ClozureCL?

**Comment by Hamayama** [comment]
I searched and found the following information.
( `*foo*` becomes a thread local variable? )

https://stackoverflow.com/questions/12156902/unexpected-behavior-with-eval-when/12165794#12165794

https://lists.clozure.com/pipermail/openmcl-devel/2009-December/006580.html

**Comment by svetlyak40wt** [comment]
Do you have an idea how to fix it?

**Comment by Hamayama** [comment]
Uhm, it might not be a thread variable preblem.

I ran lem in sbcl-bin/2.0.0 and ran swank-server in ccl-bin/1.11.5
and got tcp/ip communication log by WiresharkPortable (on Windows) .

```
==> ... (:emacs-rex (swank:compile-string-for-emacs "(defparameter *foo* \"bar\")" "foo.lisp" (quote ((:position 1) (:line 1 26))) #A((28) common-lisp:base-char . "./foo.lisp") nil) "COMMON-LISP-USER" T 20)
<== ... (:reader-error "(:emacs-rex (swank:compile-string-for-emacs \"(defparameter *foo* \\\"bar\\\")\" \"foo.lisp\" (quote ((:position 1) (:line 1 26))) #A((28) common-lisp:base-char . \"./foo.lisp\") nil) \"COMMON-LISP-USER\" T 20)" "Reader error on #<STRING-INPUT-STREAM  :CLOSED #x2100EBF29D>:
         reader macro #A used without a rank integer")
```

reader macro #A error ???

**Comment by Hamayama** [comment]
The following patch might be work.
( modes/lisp-mode/swank-protocol.lisp )

But, I don't know it causes another problem or not ...

```
--- swank-protocol_orig.lisp	2020-02-01 20:50:24.000000000 +0900
+++ swank-protocol.lisp	2020-02-04 21:48:08.870120400 +0900
@@ -41,7 +41,8 @@
 (defmacro with-swank-syntax (() &body body)
   `(with-standard-io-syntax
      (let ((*package* (find-package :swank-io-package))
-           (*print-case* :downcase))
+           (*print-case* :downcase)
+           (*print-readably* nil))
        ,@body)))
 
 ;;; Encoding and decoding messages
```

**Comment by Hamayama** [comment]
Uum, `*print-readably*` is related to read/write invariance?
Difficult to me ...

**Comment by svetlyak40wt** [comment]
I see that `*print-readably* is NIL by default on CCL:

```
Clozure Common Lisp Version 1.12-dev (v1.12-dev.5) DarwinX8664

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? *print-readably*
NIL
```

**Comment by svetlyak40wt** [comment]
I don't know what `#A((28) common-lisp:base-char . \"./foo.lisp\") nil)` is, but seems it is supported in SBCL:

```
CL-USER> #A((28) 'common-lisp:base-char . "./foo.lisp")
; Debugger entered on #<SIMPLE-ERROR "There are ~W elements in the :INITIAL-CONTENTS, but the vector length is ~W." {1004B80173}>
[1] CL-USER>
; Evaluation aborted on #<SIMPLE-ERROR "There are ~W elements in the :INITIAL-CONTENTS, but the vector length is ~W." {1004B80173}>
CL-USER> #A((10) common-lisp:base-char . "./foo.lisp")
"./foo.lisp"
```

but does not in CCL:

```
? #A((10) common-lisp:base-char . "./foo.lisp")

> Error: Reader error on #<CCL::RECORDING-CHARACTER-INPUT-STREAM #x3020004D04AD>, near position 2:
>        reader macro #A used without a rank integer
> While executing: CCL::SIGNAL-READER-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

Seems CCL's reader requires  another format for `#A` dispatch macro.

**Comment by svetlyak40wt** [comment]
@Hamayama the patch you gave works! How about merging it into the master?

**Comment by svetlyak40wt** [comment]
Great! Thank you, @Hamayama!
