### ISSUE TITLE
[vi-mode] :w does not touch the file when nothing is written.

### ISSUE THREAD

**Issue by leegbestand** [cxxxr/lem#487]
Executing `:w`(or its alternatives) does not write to a file when nothing is written by the user. This behaviour is not compatible with vi(m) and results in the stats of the file not being changed. Vi(m) does change the stats even when nothing is written. 

### Reproduce the problem
execute `stat <filename>`
Open <filename> in lem with vi-mode enabled and execute `:wq`
Now, execute  `stat <filename>` again and see that the time did not change. I expect updated time values on the file.

**Comment by gos-k** [comment]
I fixed. https://github.com/cxxxr/lem/commit/f2cc39b63fe32b5cc603f1753b6990bbf268ec9a

**Comment by leegbestand** [comment]
Wow, that's quick! Thanks a lot for the quick fix and it works as expected.
