### ISSUE TITLE
completion時のbackspaceの挙動

### ISSUE THREAD

**Issue by snmsts** [cxxxr/lem#49]
## 質問状況の再現方法

``C-x C-f  C-i backspace`` 

*  ``C-x C-f`` を叩いた時点では ``/home/user/``等 (同ディレクトリには補完対象のサブディレクトリはそれなりに入っている前提)

* 上記状態から``C-i``押下で補完用のバルーンを表示させる。
* バルーンの表示されている状態で、backspace 押下で ``#\LATIN_SMALL_LETTER_C_WITH_ACUTE`` がミニバッファに挿入されている模様。

## 質問
ここの挙動は(define-key *completion-mode-keymap* "[backspace]" ...)で変更できない？

よろしくお願いします。

**Comment by cxxxr** [comment]
> ここの挙動は(define-key completion-mode-keymap "[backspace]" ...)で変更できない？

できます


マイナーモードではmake-keymapでundef-hookを設定していると、そのマイナーモードのキーマップにキーバインドが定義されていなかったときにメジャーモードのキーマップより優先して呼び出されます

[backspace]は*completion-mode-keymap*に割り当てられていないので
undef-hookに設定されているcompletion-self-insertが呼ばれています

その中の`insertion-key-p`関数でそのキーがバッファに挿入して良いかを判定して挿入するかどうかを決めているんですが、そこで[backspace]が挿入していいものと扱われてしまっています

この判定はasciiコード範囲内ならうまくいくはずなんですが、キーコードが128以上だと
どう扱えばいいかわかっていなくておかしな文字が挿入されているんですね

どうやって判断すればいいんでしょう…

**Comment by snmsts** [comment]
対応ありがとうございます。

``insert-key-p``の問題はそれはそれとして了解しています。(虱潰し以外で簡単な方法は無さそう…)

https://github.com/cxxxr/lem/commit/272bc59f20dca7afedc296be4d7d8c035c5c61f1 
このコミットの結果、``C-h``は想定通り(一文字削除)の動きをしているように見えるのだけれど、``[backspace]``叩いた時にあいかわらず``ć``が挿入されて、``completion-delete-prevous-char``がちゃんと呼ばれているように思えない…
というのが趣旨でございました。

cxxxrさんの環境で再現していないようだとどうしようかなぁ…

**Comment by cxxxr** [comment]
一文字削除した後もcompletion-modeを継続する動作には変えましたが
`C-h`は元から一文字削除が出来ます

コミット後の変更が反映されていないとかは無いですかね

**Comment by snmsts** [comment]
どうだろう…

```
ros use sbcl-bin
rm -rf ~/.cache/common-lisp/
ros update lem
lem
```

で手元では駄目そう。

**Comment by cxxxr** [comment]
ncursesの問題かな

**Comment by snmsts** [comment]
そっか…

**Comment by snmsts** [comment]
ダンプを削除したら直りました。

**Comment by snmsts** [comment]
dumpが更新されないのはroswellのせいでした…面目ない…

https://github.com/roswell/roswell/commit/b58a107fafd561d11a947a95a53b2df7b70018dd
