### ISSUE TITLE
c-mode

### ISSUE THREAD

**Issue by snmsts** [cxxxr/lem#51]
I should assign it to me.

自分でやれ…って奴です…

**Comment by snmsts** [comment]
関連トピックとしては外部でメンテナンスされているモジュールとの結合をlemではどうやるのか？というあたり。

**Comment by cxxxr** [comment]
tmlanguageとかですかね

**Comment by snmsts** [comment]
emacsの文脈だとel-getとかかな…と思いましたがtmlanguage良いんですかね。(初見)

**Comment by cxxxr** [comment]
tmlanguageは他のエディタでも広く使われてるのでそのまま持ってこられると楽だと思いました

それとは別にpluginやextensionと言われているものの管理をlemでもしようって話でしたか
適当に書いてros installすればそのまま使えるんですけど
雛形用意したり読み込み部分を楽にするのがいいのかな

**Comment by snmsts** [comment]
つまり設定は自力でrcファイル内でql:quickloadしてあとはよしなに…な感じですね。
push

**Comment by cxxxr** [comment]
そういえばneovim等ではrpcでやりとりする機能があるんですね
そういうのは出来るようにしたい

**Comment by cxxxr** [comment]
使い込んでないので粗はあるかもしれませんが、シンタックスハイライトと
インデントは大体動くようになりました

**Comment by snmsts** [comment]
ありがとうございます。試してみます。closeかな…
