### ISSUE TITLE
Error installing lem via roswell

### ISSUE THREAD

**Issue by analyticd** [cxxxr/lem#55]
Here is the stack trace (on macOS Sierra):

ros install cxxxr/lem
install from github cxxxr/lem
To load "lem":
  Load 1 ASDF system:
    lem
; Loading "lem"
............[1/3] System 'lem' found. Loading the system..

; file: /Users/username/.roswell/lisp/quicklisp/dists/quicklisp/software/cffi_0.17.1/toolchain/asdf-compat.lisp
; in: DEFUN BUNDLE-PATHNAME-TYPE
;     ((UIOP/OS:OS-UNIX-P) "o")
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-WINDOWS-P)
;      (IF (UIOP/OS:FEATUREP '(:OR :MINGW32 :MINGW64))
;          "o"
;          "obj"))
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-UNIX-P) "a")
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-WINDOWS-P)
;      (IF (UIOP/OS:FEATUREP '(:OR :MINGW32 :MINGW64))
;          "a"
;          "lib"))
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-MACOSX-P) "dylib")
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-UNIX-P) "so")
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-WINDOWS-P) "dll")
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-UNIX-P) NIL)
; 
; caught ERROR:
;   illegal function call

;     ((UIOP/OS:OS-WINDOWS-P) "exe")
; 
; caught ERROR:
;   illegal function call
.Aborted during step [1/3].
Unhandled LOAD-SYSTEM-DEFINITION-ERROR: Error while trying to load definition for system cl-charms from pathname /Users/username/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-charms-20160318-git/cl-charms.asd: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002DE7483}>
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1006F036FB}>)
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {1006F036CB}>)
3: (SB-DEBUG:PRINT-BACKTRACE :STREAM #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDERR* {10001530A3}> :START 0 :FROM :INTERRUPTED-FRAME :COUNT NIL :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)
4: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<LOAD-SYSTEM-DEFINITION-ERROR {1006EFAFB3}> #<unavailable argument>)
5: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<LOAD-SYSTEM-DEFINITION-ERROR {1006EFAFB3}>)
6: (INVOKE-DEBUGGER #<LOAD-SYSTEM-DEFINITION-ERROR {1006EFAFB3}>)
7: (ERROR LOAD-SYSTEM-DEFINITION-ERROR :NAME "cl-charms" :PATHNAME #P"/Users/username/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-charms-20160318-git/cl-charms.asd" :CONDITION #<COMPILE-FILE-ERROR {1006EFAE53}>)
8: ((FLET #:HANDLER1452 :IN ASDF/FIND-SYSTEM:LOAD-ASD) #<COMPILE-FILE-ERROR {1006EFAE53}>)
9: (SIGNAL #<COMPILE-FILE-ERROR {1006EFAE53}>)
10: (ERROR COMPILE-FILE-ERROR :CONTEXT-FORMAT "~/asdf-action::format-action/" :CONTEXT-ARGUMENTS ((#<COMPILE-OP > . #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat">)))
11: (CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<COMPILE-OP > . #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat">)))
12: ((SB-PCL::EMF PERFORM) #<unavailable argument> #<unavailable argument> #<COMPILE-OP > #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat">)
13: ((:METHOD PERFORM-WITH-RESTARTS :AROUND (T T)) #<COMPILE-OP > #<CL-SOURCE-FILE "cffi-toolchain" "toolchain" "asdf-compat">) [fast-method]
14: ((:METHOD PERFORM-PLAN (LIST)) ((#1=#<PREPARE-OP > . #2=#<SYSTEM "uiop">) (#3=#<COMPILE-OP > . #2#) (#4=#<LOAD-OP > . #2#) (#1# . #<SYSTEM #5="alexandria">) (#1# . #6=#<STATIC-FILE #5# "LICENCE">) (#3# . #6#) (#4# . #6#) (#1# . #7=#<STATIC-FILE #5# "tests.lisp">) (#3# . #7#) (#4# . #7#) (#1# . #8=#<CL-SOURCE-FILE #5# "package">) (#4# . #8#) ...) :FORCE NIL) [fast-method]
15: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
16: ((:METHOD PERFORM-PLAN :AROUND (T)) ((#1=#<PREPARE-OP > . #2=#<SYSTEM "uiop">) (#3=#<COMPILE-OP > . #2#) (#4=#<LOAD-OP > . #2#) (#1# . #<SYSTEM #5="alexandria">) (#1# . #6=#<STATIC-FILE #5# "LICENCE">) (#3# . #6#) (#4# . #6#) (#1# . #7=#<STATIC-FILE #5# "tests.lisp">) (#3# . #7#) (#4# . #7#) (#1# . #8=#<CL-SOURCE-FILE #5# "package">) (#4# . #8#) ...)) [fast-method]
17: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
18: ((:METHOD PERFORM-PLAN :AROUND (T)) #<SEQUENTIAL-PLAN {10033DBC03}>) [fast-method]
19: ((:METHOD OPERATE (OPERATION COMPONENT)) #<LOAD-OP > #<SYSTEM "cffi-grovel">) [fast-method]
20: ((SB-PCL::EMF OPERATE) #<unused argument> #<unused argument> #<LOAD-OP > #<SYSTEM "cffi-grovel">)
21: ((LAMBDA NIL :IN OPERATE))
22: ((:METHOD OPERATE :AROUND (T T)) #<LOAD-OP > #<SYSTEM "cffi-grovel">) [fast-method]
23: ((SB-PCL::EMF OPERATE) #<unused argument> #<unused argument> LOAD-OP #<SYSTEM "cffi-grovel">)
24: ((LAMBDA NIL :IN OPERATE))
25: ((:METHOD OPERATE :AROUND (T T)) LOAD-OP #<SYSTEM "cffi-grovel">) [fast-method]
26: (LOAD-SYSTEM #<SYSTEM "cffi-grovel">)
27: (LOAD-SYSTEMS* (#<SYSTEM "cffi-grovel">))
28: ((LAMBDA NIL :IN ASDF/PARSE-DEFSYSTEM:REGISTER-SYSTEM-DEFINITION))
29: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEFSYSTEM #:CL-CHARMS :VERSION (:READ-FILE-FORM "version.lisp-expr") :MAINTAINER "Mark Fedurin <hitecnologys@gmail.com>" :AUTHOR "Abhishek Reddy <abhishek@abhishek.geek.nz>" :DESCRIPTION "CFFI bindings for curses." :LICENSE "MIT License (See COPYING)" ...) #<NULL-LEXENV>)
30: (SB-EXT:EVAL-TLF (DEFSYSTEM #:CL-CHARMS :VERSION (:READ-FILE-FORM "version.lisp-expr") :MAINTAINER "Mark Fedurin <hitecnologys@gmail.com>" :AUTHOR "Abhishek Reddy <abhishek@abhishek.geek.nz>" :DESCRIPTION "CFFI bindings for curses." :LICENSE "MIT License (See COPYING)" ...) 0 #<NULL-LEXENV>)
31: ((FLET SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (DEFSYSTEM #:CL-CHARMS :VERSION (:READ-FILE-FORM "version.lisp-expr") :MAINTAINER "Mark Fedurin <hitecnologys@gmail.com>" :AUTHOR "Abhishek Reddy <abhishek@abhishek.geek.nz>" :DESCRIPTION "CFFI bindings for curses." :LICENSE "MIT License (See COPYING)" ...) 0)
32: ((LAMBDA (SB-KERNEL:FORM &KEY SB-FASL::CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (DEFSYSTEM #:CL-CHARMS :VERSION (:READ-FILE-FORM "version.lisp-expr") :MAINTAINER "Mark Fedurin <hitecnologys@gmail.com>" :AUTHOR "Abhishek Reddy <abhishek@abhishek.geek.nz>" :DESCRIPTION "CFFI bindings for curses." :LICENSE "MIT License (See COPYING)" ...) :CURRENT-INDEX 0)
33: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY SB-FASL::CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {100323A28B}> #<SB-C::SOURCE-INFO {100323A243}> SB-C::INPUT-ERROR-IN-LOAD)
34: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /Users/username/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-charms-20160318-git/cl-charms.asd" {1003235FB3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
35: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file /Users/username/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-charms-20160318-git/cl-charms.asd" {1003235FB3}> NIL)
36: (LOAD #P"/Users/username/.roswell/lisp/quicklisp/dists/quicklisp/software/cl-charms-20160318-git/cl-charms.asd" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :UTF-8)
37: (CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN LOAD*) {10032301EB}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
38: ((LAMBDA NIL :IN ASDF/FIND-SYSTEM:LOAD-ASD))
39: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN ASDF/FIND-SYSTEM:LOAD-ASD) {100323000B}>)
40: ((LAMBDA NIL :IN FIND-SYSTEM))
41: (ASDF/CACHE:CONSULT-ASDF-CACHE (FIND-SYSTEM "cl-charms") #<CLOSURE (LAMBDA NIL :IN FIND-SYSTEM) {100320C76B}>)
42: ((:METHOD FIND-SYSTEM (STRING)) "cl-charms" NIL) [fast-method]
43: ((:METHOD FIND-COMPONENT (STRING T)) "cl-charms" NIL) [fast-method]
44: (ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<SYSTEM "lem-core"> "cl-charms" NIL)
45: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<SEQUENTIAL-PLAN {1005F13CD3}> #<PREPARE-OP > #<SYSTEM "lem-core"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {100320C3AB}>)
46: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
47: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<SEQUENTIAL-PLAN {1005F13CD3}> #<PREPARE-OP > #<SYSTEM "lem-core"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {100320C34B}>) [fast-method]
48: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<SEQUENTIAL-PLAN {1005F13CD3}> #<PREPARE-OP > #<CL-SOURCE-FILE "lem-core" "history"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {100320BF6B}>)
49: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
50: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<SEQUENTIAL-PLAN {1005F13CD3}> #<PREPARE-OP > #<CL-SOURCE-FILE "lem-core" "history"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {100320BF0B}>) [fast-method]
51: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<SEQUENTIAL-PLAN {1005F13CD3}> #<LOAD-OP > #<CL-SOURCE-FILE "lem-core" "history"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {100320BB1B}>)
52: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
53: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<SEQUENTIAL-PLAN {1005F13CD3}> #<LOAD-OP > #<CL-SOURCE-FILE "lem-core" "history"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {100320BABB}>) [fast-method]
54: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<SEQUENTIAL-PLAN {1005F13CD3}> #<LOAD-OP > #<SYSTEM "lem-core"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {100320B6CB}>)
55: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
56: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<SEQUENTIAL-PLAN {1005F13CD3}> #<LOAD-OP > #<SYSTEM "lem-core"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {100320B66B}>) [fast-method]
57: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<SEQUENTIAL-PLAN {1005F13CD3}> #<PREPARE-OP > #<SYSTEM "lem"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1005F14DBB}>)
58: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
59: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<SEQUENTIAL-PLAN {1005F13CD3}> #<PREPARE-OP > #<SYSTEM "lem"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {1005F14D5B}>) [fast-method]
60: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<SEQUENTIAL-PLAN {1005F13CD3}> #<LOAD-OP :VERBOSE NIL> #<SYSTEM "lem"> #<CLOSURE (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {1005F148FB}>)
61: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
62: ((:METHOD ASDF/PLAN:CALL-WHILE-VISITING-ACTION (ASDF/PLAN:PLAN-TRAVERSAL T T T)) #<SEQUENTIAL-PLAN {1005F13CD3}> #<LOAD-OP :VERBOSE NIL> #<SYSTEM "lem"> #<CLOSURE (LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION) {1005F1489B}>) [fast-method]
63: ((:METHOD MAKE-PLAN (T OPERATION COMPONENT)) NIL #<LOAD-OP :VERBOSE NIL> #<SYSTEM "lem"> :VERBOSE NIL) [fast-method]
64: ((:METHOD OPERATE (OPERATION COMPONENT)) #<LOAD-OP :VERBOSE NIL> #<SYSTEM "lem"> :VERBOSE NIL) [fast-method]
65: ((SB-PCL::EMF OPERATE) #<unused argument> #<unused argument> #<LOAD-OP :VERBOSE NIL> #<SYSTEM "lem"> :VERBOSE NIL)
66: ((LAMBDA NIL :IN OPERATE))
67: ((:METHOD OPERATE :AROUND (T T)) #<LOAD-OP :VERBOSE NIL> #<SYSTEM "lem"> :VERBOSE NIL) [fast-method]
68: ((SB-PCL::EMF OPERATE) #<unused argument> #<unused argument> LOAD-OP "lem" :VERBOSE NIL)
69: ((LAMBDA NIL :IN OPERATE))
70: (ASDF/CACHE:CALL-WITH-ASDF-CACHE #<CLOSURE (LAMBDA NIL :IN OPERATE) {1005F090BB}> :OVERRIDE NIL :KEY NIL)
71: ((:METHOD OPERATE :AROUND (T T)) LOAD-OP "lem" :VERBOSE NIL) [fast-method]
72: ((:METHOD OPERATE :AROUND (T T)) LOAD-OP "lem" :VERBOSE NIL) [fast-method]
73: (LOAD-SYSTEM "lem" :VERBOSE NIL)
74: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1005EF0B8B}>)
75: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "lem" :PROMPT NIL)
76: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unavailable argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1005EDE69B}>) [fast-method]
77: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {1006ECC633}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1005EDE69B}>) [fast-method]
78: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) #<unavailable argument> :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
79: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {1005ED1C2B}>)
80: (ROSWELL.INSTALL:INSTALL-SYSTEM-SCRIPT "lem")
81: (ROSWELL.INSTALL:INSTALL-SYSTEM-IF-PROBED "lem")
82: (ROSWELL.INSTALL:INSTALL #<unavailable argument>)
83: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE ROS.SCRIPT.INSTALL.3671936092::MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
84: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.INSTALL.3671936092::MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
85: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.INSTALL.3671936092::MAIN) ROSWELL:*ARGV*)) NIL #<NULL-LEXENV>)
86: ((FLET SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE ROS.SCRIPT.INSTALL.3671936092::MAIN) ROSWELL:*ARGV*)) NIL)
87: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {1003592A73}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
88: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {1003592A73}> NIL)
89: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {1003592A73}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
90: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /usr/local/Cellar/roswell/17.7.9.80/etc/roswell/install.ros" {100358B3B3}>)
91: (ROSWELL:SCRIPT "/usr/local/Cellar/roswell/17.7.9.80/etc/roswell/install.ros" "cxxxr/lem")
92: (ROSWELL:RUN ((:EVAL "(ros:quicklisp)") (:SCRIPT "/usr/local/Cellar/roswell/17.7.9.80/etc/roswell/install.ros" "cxxxr/lem") (:QUIT NIL)))
93: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/usr/local/Cellar/roswell/17.7.9.80/etc/roswell/install.ros" "cxxxr/lem") (:QUIT NIL)))) #<NULL-LEXENV>)
94: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:quicklisp)") (:SCRIPT "/usr/local/Cellar/roswell/17.7.9.80/etc/roswell/install.ros" "cxxxr/lem") (:QUIT NIL)))))
95: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/usr/local/Cellar/roswell/17.7.9.80/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:quicklisp)\")(:script \"/usr/local/Cellar/roswell/17.7.9.80/etc/roswell/install.ros\"\"cxxxr/lem\")(:quit ())))")))
96: (SB-IMPL::TOPLEVEL-INIT)
97: ((FLET #:WITHOUT-INTERRUPTS-BODY-85 :IN SB-EXT:SAVE-LISP-AND-DIE))
98: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 9 ERROR conditions

**Comment by cxxxr** [comment]
Is ncurses installed?

**Comment by analyticd** [comment]
Yes, but perhaps not in the location lem expects?

**Comment by cxxxr** [comment]
Probably it has failed to install cl-charms.

**Comment by analyticd** [comment]
I thought that might be possible too. When I fire up sbcl separate from
roswell, (ql:quickload :cl-charms) installs without issue. Not sure if
same is true of roswell managed install.

**Comment by cxxxr** [comment]
@snmsts Is this issue due to roswell?

**Comment by snmsts** [comment]
don't know.
