### ISSUE TITLE
Ctrl-k（kill line)の動作が遅い

### ISSUE THREAD

**Issue by ta2gch** [cxxxr/lem#64]
こんにちは。
以下の環境でのlemのCtrl-Kを押した時の行が削除されるまでの時間が他のエディタに比べて遅いです。

| OS | macOS |
| -|-|
| **Verison** | **010a480**   |

Cursesの問題かもしれませんが、その場合はEmacsの同様のコマンドやVimのdd等も遅くなるはずなので、Cursesの問題ではなくlemの方に問題があると判断しました。

よろしくお願いいたします。

![lem](https://user-images.githubusercontent.com/5019902/32587239-a2a17c78-c54a-11e7-8f65-a584370522fe.gif)

**Comment by snmsts** [comment]
https://github.com/snmsts/trivial-clipboard

もっぱらこいつのせいだという噂ですよ。

**Comment by cxxxr** [comment]
kill-ringを使うときにtrivial-clipboardを毎回呼び出してるので
C-kをする毎にrun-programを使うから遅くなってるという話ですかね

その場しのぎとしては
`(setf (fdefinition 'lem::%clipboard) (constantly nil))`
としてtrivial-clipboardを使わないようにできます

**Comment by ta2gch** [comment]
@snmsts @cxxxr 切り取った内容は毎回クリップボードにコピーしていたのですね。そしてpbcopyやxclipを実行していたのが原因だということも理解しました。ありがとうございます。当面はそのように対処します。

この動作を非同期にするのはどうでしょうか？

**Comment by cxxxr** [comment]
非同期化しました
b75837a64464544cbbfab57fdf5cda26a97ae436

**Comment by ta2gch** [comment]
すばらしいです！make-threadを使っているようですが、Roswell的には大丈夫なのでしょうか。SBCLのスレッド機能はバイナリだとサポートしていない時があった気がします。

**Comment by cxxxr** [comment]
エディタのコア部分でbordeaux-threadsに依存しているので既にスレッドのサポートは必須になっています

**Comment by snmsts** [comment]
ぼくはしらんよ。

**Comment by ta2gch** [comment]
すでにスレッド機能が必須になっていたのですね。承知しました。
ros scriptのビルドはSBCL-BINでビルドされていると思っていたので心配したのですが大丈夫そうですね。
よく考えたらuseで設定した処理系でビルドしてるはずですね。お騒がせしました。

**Comment by ta2gch** [comment]
useした処理系でros scriptはビルドされる訳ではなくやはりsbcl-binでビルドされていました。しかしスレッドは有効化されていたため問題が解決されていることを確認しました。
