### ISSUE TITLE
Thank you so much.

### ISSUE THREAD

**Issue by azzamsa** [cxxxr/lem#66]
>Lem makes it possible to develop software using Common Lisp once you install it on your computer. You don't need any tidy setting on Emacs. You don't need to install any other plugin. Lem is the best editor for developers using Common Lisp.

You really made my days warm.
Thank you so much for this project and your faculty.

Hope you always healthy and successful

Happy hacking.

PS: sorry for writing here, I do not find your email address nor your blog, I hope I can write you an email soon.

**Comment by stacksmith** [comment]
@cxxxr 
 I deeply appreciate your project. Think of me as a resource. The code I submit is always a suggestion. If your ideas are different, please let me know.

私はあなたのプロジェクトに深く感謝します。 私をリソースと考えてください。 私が提出するコードは、常に提案です。 あなたのアイデアが異なる場合は、私に知らせてください。

**Comment by snmsts** [comment]
@stacksmith  Japanese translation of "Think of me as a resource" sounds like you are kind a material we(he?) can consume. a bit scary...
Anyway, Think of me as an interface for you to him. :)
What I like about lem is less ambitious than climacs,it provide us a joy of hacking  and it takes trivial patch!
I hope lem become richer to be a choice for people who stop using emacs.
Any contributions are literally welcomed.

**Comment by stacksmith** [comment]
@snmsts - got it.  
Using the same Lisp to program the editor makes a lot more sense.

**Comment by snmsts** [comment]
This isn't issue to do something. so close.
