### ISSUE TITLE
can't run on SBCL

### ISSUE THREAD

**Issue by azzamsa** [cxxxr/lem#67]
I try to follow installation instruction.

I can install using roswell, then move it to quicklisp `local-project`, load it with quickload successfully but get an eror when running `(lem:lem)`

``` lisp
CL-USER> (lem:lem)
The variable LEM.TERM::*COLORS* is unbound.
Backtrace for: #<SB-THREAD:THREAD "editor" RUNNING {10041CBFD3}>
0: (LEM.TERM::GET-COLOR-RGB 119 119 119)
1: (LEM.TERM::GET-COLOR "#777777")
2: (LEM.TERM:GET-COLOR-PAIR "#777777" "#bbbbbb")
3: (LEM::ATTRIBUTE-TO-BITS LEM:MODELINE-INACTIVE)
4: ((:METHOD LEM::INTERFACE-PRINT-MODELINE ((EQL :NCURSES) T T T T T)) #<unavailable argument> #S(LEM::NCURSES-VIEW :SCRWIN #.(SB-SYS:INT-SAP #X7FFFE40144F0) :MODELINE-SCRWIN #.(SB-SYS:INT-SAP #X7FFFE401D540) :X 0 :Y 11 :WIDTH 103 :HEIGHT 11) 0 0 "                                                                                                       " LEM:MODELINE-INACTIVE) [fast-method]
5: (LEM::SCREEN-REDRAW-MODELINE #<LEM::WINDOW {1005E945C3}> T)
6: (LEM::REDRAW-DISPLAY-WINDOW #<LEM::WINDOW {1005E945C3}> NIL)
7: (LEM:REDRAW-DISPLAY NIL)
8: ((FLET #:H0 :IN LEM::TOPLEVEL-COMMAND-LOOP) #<UNBOUND-VARIABLE *COLORS* {1005E936D3}>)
9: (SIGNAL #<UNBOUND-VARIABLE *COLORS* {1005E936D3}>)
10: (ERROR UNBOUND-VARIABLE :NAME LEM.TERM::*COLORS*)
11: ("UNBOUND-SYMBOL-ERROR" LEM.TERM::*COLORS*)
12: (SB-KERNEL:INTERNAL-ERROR #.(SB-SYS:INT-SAP #X7FFFEF535D40) #<unavailable argument>)
13: ("foreign function: call_into_lisp")
14: ("foreign function: funcall2")
15: ("foreign function: interrupt_internal_error")
16: ("foreign function: handle_trap")
17: ("foreign function: #x414773")
18: (LEM.TERM::GET-COLOR-RGB 0 0 0)
19: (LEM.TERM::GET-COLOR "black")
20: (LEM.TERM:GET-COLOR-PAIR "black" "#bbbbbb")
21: (LEM::ATTRIBUTE-TO-BITS LEM:MODELINE)
22: ((:METHOD LEM::INTERFACE-REDRAW-VIEW-AFTER ((EQL :NCURSES) T T)) :NCURSES #S(LEM::NCURSES-VIEW :SCRWIN #.(SB-SYS:INT-SAP #X7FFFE40136A0) :MODELINE-SCRWIN NIL :X 0 :Y 23 :WIDTH 103 :HEIGHT 1) NIL) [fast-method]
23: (LEM::REDRAW-DISPLAY-WINDOW #<LEM::MINIBUFFER-WINDOW {1005847653}> T)
24: (LEM:REDRAW-DISPLAY T)
25: (LEM-BASE:RUN-HOOKS ((#<FUNCTION (LAMBDA NIL :IN "/home/myusername/quicklisp/local-projects/lem/lem-ncurses/ncurses.lisp") {22778E0B}> . 0)))
26: (LEM::INIT #S(LEM::COMMAND-LINE-ARGUMENTS :ARGS NIL :NO-INIT-FILE NIL))
27: (LEM::TOPLEVEL-COMMAND-LOOP #<CLOSURE (LAMBDA NIL :IN LEM::RUN-EDITOR-THREAD) {1005849B7B}>)
28: ((LAMBDA NIL :IN LEM::RUN-EDITOR-THREAD))
29: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
30: ((FLET #:WITHOUT-INTERRUPTS-BODY-1139 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
31: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
32: ((FLET #:WITHOUT-INTERRUPTS-BODY-359 :IN SB-THREAD::CALL-WITH-MUTEX))
33: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFEF536D6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "editor" RUNNING {10041CBFD3}>> NIL T NIL)
34: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "editor" RUNNING {10041CBFD3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {10041CBF7B}> (#<SB-THREAD:THREAD "editor" RUNNING {10041CBFD3}> #<SB-THREAD:THREAD "repl-thread" RUNNING {100314FFA3}> #<SB-THREAD:THREAD "auto-flush-thread" RUNNING {100314FDA3}> #<SB-THREAD:THREAD "swank-indentation-cache-thread" RUNNING {1002FA8173}> #<SB-THREAD:THREAD "reader-thread" RUNNING {1002FA8063}> #<SB-THREAD:THREAD "control-thread" RUNNING {1002FA7663}> #<SB-THREAD:THREAD "Swank Sentinel" RUNNING {1002D1E543}> #<SB-THREAD:THREAD "main thread" RUNNING {1001E06C33}>) NIL NIL NIL NIL)
35: ("foreign function: call_into_lisp")
36: ("foreign function: new_thread_trampoline")

NIL
CL-USER> 
```

SBCL 1.3.14.debian
SLIME 2.20
Quicklisp 2016-02-22

****
Update 27.11.2017 9:50 PM

I can run it with 

- cd /home/myusername/.roswell/bin/
- ./lem

**Comment by hiroki802** [comment]
Have you installed the ncurses library?
It seems that the error is happening around ncurses.

https://www.cyberciti.biz/faq/linux-install-ncurses-library-headers-on-debian-ubuntu-centos-fedora

**Comment by azzamsa** [comment]
I can run `lem` immediately in my bash prompt after adding `roswell/bin` to my `PATH`.

These the screenshoot 
- https://i.imgur.com/AnerdYl.png 
- https://i.imgur.com/4Hb37PX.png

but It will fail when I try to run with SLIME using `quickload`


as I discussed [here](https://www.reddit.com/r/Common_Lisp/comments/7fv6y6/lem/)

**Comment by cxxxr** [comment]
Did you solved?

**Comment by azzamsa** [comment]
Yes. it is *solved* when I run with `roswell` but *failed* when I run using `quickload`

**Comment by stacksmith** [comment]
Some thoughts: try quickloading :lem-ncurses.  lem requires a frontend for a display mechanism.  The command-line script hides this from you.  Having said this, ncurses needs a terminal to run in - a SLIME buffer is not good enough.  So if you are running inside emacs, this ncurses will not work.  Try `cat ~/.roswell/bin/lem` and `lem-ncurses` to see what it does.

**Comment by azzamsa** [comment]
I have tried quickloading `:lem-ncurses`, but in the end, running `(lem:lem)` still get the same error as above `The variable LEM.TERM::*COLORS* is unbound.`

**Comment by stacksmith** [comment]
@azzamsa - if you can load :lem-ncurses without errors, it really should work.

1) What version of SBCL are you running?
2) Are you sure you are not inside Emacs when you run (lem:lem)? That does not work!
3) Instead of copying after installing with roswell, do this:
- Edit ~/.sbclrc
- After `(pushnew (truename "~/Documents/lisp/") ql:*local-project-directories* )`, add a line for your roswell local directories.  It is probably 
`(pushnew (truename "~/Documents/config/.roswell/local-projects") ql:*local-project-directories* )` - check that it makes sense and has the cxxxr/lem in it.
- Get rid of the copy you made in your old local directory.
Now, from the command line:
```
SBCL
(ql:quickload :lem-ncurses)
(lem:lem)
```


This way, at least you know *which* lem you are running.

Again

**Comment by stacksmith** [comment]
I am pretty sure you are in Emacs - I get the same error from Emacs.  Emacs repl is not a terminal and does not support ncurses!  If you want ncurses, start from the command line.

**Comment by azzamsa** [comment]
@stacksmith oh, I think I don't get the installation guide carefully.

Yes, I successfully quickload everything.

 >Are you sure you are not inside Emacs when you run (lem:lem)? That does not work!
This is my mistake.

I always run `(lem:lem)` inside slime buffer.

And when I run `lem` in terminal and it is work.

I think I have to run `(lem:lem)` in emacs buffer, because the readme (months ago) have two section, running with quickload and with terminal (roswell), so I think I can launch it directly from slime buffer as my other web application.

Yes, I know ncurses, I have some favorite app depend highly on it.


Thanks lot for pointing it out, Stacksmith.

**Comment by azzamsa** [comment]
So I think I can close this issue now.

**Comment by stacksmith** [comment]
Yes, ncurses will never work from emacs.  I am about to publish an X front end for lem, which you can start from emacs...:)

**Comment by azzamsa** [comment]
X front-end, you mean GTK binding from lem ?

**Comment by stacksmith** [comment]
No, custom XCB bindings for X, freetype2 for subpixel-antialiased fonts.

**Comment by azzamsa** [comment]
sorry to ask, but why you choose xcb instead of xlib(GTK+) ?

**Comment by stacksmith** [comment]
xcb is a much better thread-safe interface to X ; xlib is kind of obsolete.  GTK+ is a monstrosity, and having worked with it I will do anything to avoid using it!  All we need here is nice looking monospaced text - a minimal solution is faster and cleaner.

**Comment by azzamsa** [comment]
> a  minimal solution is faster and cleaner.

Great works, thank you so much for your contribution.

**Comment by stacksmith** [comment]
OT: @azzamsa - try the XCB branch of https://github.com/stacksmith/lem
