### ISSUE TITLE
make-buffer-output-stream is too slow

### ISSUE THREAD

**Issue by KeenS** [cxxxr/lem#8]
You can feel the speed by using `describe-bindings` (#7). Maybe you need to rewrite write-sequence ((stream buffer-output-stream) sequence  start end &keys) not to use `stream-write-char`.

**Comment by cxxxr** [comment]
日本人同士なら日本語で話すべきです
なぜなら僕が英語の読み書きが苦手で意思疎通に大きなオーバーヘッドができるからです

**Comment by KeenS** [comment]
はい。
上にも書いた通り`buffer-output-stream` が gray-streamsの`write-sequence`を実装していますが1文字毎にbufferに書き込んでいてかなり遅い（describe-bindingsを使うと体感出来る）のでsequenceのまま書き込むようにしたら良いんじゃないかという提案です。改行文字捜してlineに分割するのもそんなに難しくないと思います。

**Comment by cxxxr** [comment]
ありがとうございます
確かにそうです
write-sequenceの辺りはあまり使うことはなかったので余白を埋めるための手抜き実装でした
